/* ============================================================
   EXPLICACIONES — lote 16  (42 casos clínicos)  ÚLTIMO LOTE
   Año 2022. Con este lote quedan explicados TODOS los casos
   clinicos del banco MIR fuera de cuarentena.
   Preguntas de 4 opciones: cada no:{} lleva 3 distractores.
   Las 42 respuestas oficiales verificadas una a una.
   ============================================================ */
window.EXPLICACIONES = Object.assign(window.EXPLICACIONES || {}, {

/* ==================== HEMATOLOGÍA E INMUNOTERAPIA ==================== */
'MIR-2022-M146': {
  esp:'Medicina Interna', tema:'Hematología', sub:'Coagulación intravascular diseminada',
  clave:'En la CID los anticoagulantes naturales se CONSUMEN: antitrombina y proteína C están BAJAS, nunca elevadas.',
  exp:'El caso es una *coagulación intravascular diseminada* en el contexto de una sepsis grave: sangrado por los puntos de venopunción, *trombopenia* de 52.000, anemia con *LDH de 820* y reticulocitosis, que traducen la *hemólisis microangiopática* por el paso de los hematíes a través de la red de fibrina. El mecanismo consiste en una activación masiva y descontrolada de la coagulación que consume, a la vez, *plaquetas, factores y anticoagulantes naturales*. De ahí se deducen todos los hallazgos esperables: el *fibrinógeno baja* porque se consume; el *tiempo de protrombina y el TTPA se alargan* por el consumo de factores; y aparecen *productos de degradación de la fibrina y dímero D elevados*, porque la fibrinólisis secundaria intenta deshacer los trombos. Y por el mismo motivo, la *antitrombina y la proteína C* —que son inhibidores fisiológicos consumidos en el proceso— están *descendidas*, no elevadas: ese es el enunciado que no cabe esperar. Su descenso, además, tiene valor pronóstico. El tratamiento es el de la causa, con soporte transfusional según el sangrado.',
  no:{0:'Es esperable: el fibrinógeno se consume y desciende.',2:'Es esperable: el consumo de factores alarga los tiempos de coagulación.',3:'Es esperable: la fibrinólisis secundaria eleva el dímero D y los productos de degradación.'},
  trampa:'Se piensa que si hay trombosis los anticoagulantes naturales deben estar altos. Ocurre lo contrario: se gastan, y su caída agrava el cuadro.',
  dx:['Coagulación intravascular diseminada','Púrpura trombótica trombocitopénica','Hepatopatía','Trombopenia por heparina'],
  obj:'Conocer el perfil de laboratorio de la CID y el consumo de anticoagulantes naturales.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios ISTH de CID y Harrison, 21.ª ed.'
},
'MIR-2022-M37': {
  esp:'Medicina Interna', tema:'Inmunología', sub:'Terapia CAR-T',
  clave:'El receptor CAR reconoce el antígeno de forma INDEPENDIENTE del HLA: esa es su gran ventaja sobre el receptor T natural.',
  exp:'La clave conceptual de la terapia CAR-T está precisamente en el enunciado falso. El *receptor de células T natural* solo reconoce péptidos *presentados por moléculas del complejo mayor de histocompatibilidad*, lo que constituye un punto débil frente al tumor, porque una de las principales estrategias de escape de las células malignas es *perder la expresión de HLA de clase I*. El *receptor quimérico* se diseña justamente para sortear ese obstáculo: su porción de reconocimiento es un *fragmento variable de cadena única derivado de un anticuerpo*, de modo que se une al antígeno *directamente sobre la superficie celular*, como haría un anticuerpo, *sin necesidad de presentación por HLA*. A esa porción extracelular se le añaden un dominio transmembrana y un *dominio intracelular de señalización* —CD3 zeta más señales coestimuladoras como 4-1BB o CD28—, que es lo que activa al linfocito. Los efectos adversos característicos son el *síndrome de liberación de citocinas*, con fiebre e hipotensión, tratable con tocilizumab, y la *neurotoxicidad*.',
  no:{0:'Es correcto: el reconocimiento se basa en fragmentos variables de cadena única derivados de anticuerpos anti-CD19.',1:'Es correcto: el dominio intracelular transmite la señal de activación al linfocito.',2:'Es correcto: el síndrome de liberación de citocinas es su complicación grave más característica.'},
  trampa:'Se asume que todo reconocimiento por linfocitos T depende del HLA. La independencia del HLA es justamente el motivo de diseñar el receptor quimérico.',
  dx:[],
  obj:'Explicar el fundamento del receptor CAR y su independencia del HLA.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Abbas, Inmunología Celular y Molecular.'
},

/* ==================== ENDOCRINOLOGÍA Y NUTRICIÓN ==================== */
'MIR-2022-M160': {
  esp:'Medicina Interna', tema:'Endocrinología', sub:'Tiroiditis subaguda',
  clave:'Tiroides DOLOROSO tras un cuadro vírico, con fiebre y tirotoxicosis: tiroiditis subaguda de De Quervain.',
  exp:'La tiroiditis subaguda tiene una presentación muy reconocible. Está precedida de un *cuadro vírico de vías altas* una a tres semanas antes, como las mialgias y la tos seca que refiere la paciente. Su rasgo distintivo es el *dolor cervical anterior*, que se irradia a la mandíbula o al oído y que a menudo se confunde con una faringitis, aunque la exploración de la faringe sea *normal* y lo que duele a la palpación sea la propia *glándula tiroidea*. Y se acompaña de *tirotoxicosis transitoria* —temblor, sudoración, taquicardia de 110— que no se debe a una hiperproducción de hormona sino a la *liberación pasiva* del contenido de los folículos destruidos por la inflamación. Por eso la captación en la gammagrafía está *abolida*, dato que la separa de la enfermedad de Graves, y por eso el tratamiento no son antitiroideos sino *antiinflamatorios* —AINE, y corticoides si el dolor es intenso— junto con betabloqueantes sintomáticos. La evolución típica atraviesa una fase de hipotiroidismo transitorio antes de recuperarse.',
  no:{1:'La tiroiditis linfocitaria es INDOLORA y no cursa con fiebre ni dolor cervical.',2:'La tiroiditis aguda infecciosa es rara, cursa con signos inflamatorios locales intensos, absceso y afectación séptica.',3:'La enfermedad de Graves es INDOLORA y su instauración es progresiva, con bocio difuso, captación aumentada y a menudo oftalmopatía.'},
  trampa:'Se trata como una faringitis por la odinofagia. Lo que duele es el tiroides, y palparlo cambia el diagnóstico.',
  dx:['Tiroiditis subaguda de De Quervain','Tiroiditis aguda supurada','Enfermedad de Graves','Faringoamigdalitis'],
  obj:'Reconocer la tiroiditis subaguda por el dolor tiroideo y la tirotoxicosis transitoria.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías de la American Thyroid Association sobre tirotoxicosis.'
},
'MIR-2022-M159': {
  esp:'Medicina Interna', tema:'Oncología', sub:'Carcinoma medular de tiroides',
  clave:'En TODO carcinoma medular hay que estudiar el protooncogén RET: hasta un cuarto son hereditarios y no se detectan por la clínica.',
  exp:'El carcinoma medular deriva de las *células C parafoliculares* y representa alrededor del 3-5% de los cánceres de tiroides, es decir, es el *tercero* en frecuencia tras el papilar y el folicular, no el segundo. Aproximadamente el *75% son esporádicos* y el *25% hereditarios*, formando parte de un *MEN 2A*, un *MEN 2B* o del carcinoma medular familiar. La recomendación establecida es realizar *estudio germinal de RET a todos los pacientes*, incluidos los aparentemente esporádicos, porque una proporción apreciable de estos resulta portadora de mutación germinal no sospechada, con consecuencias enormes: obliga a cribar feocromocitoma e hiperparatiroidismo en el propio paciente y a estudiar a la familia, ofreciendo *tiroidectomía profiláctica* a los portadores. Dos precisiones más: el seguimiento bioquímico se hace con *calcitonina y CEA*, nunca con *tiroglobulina*, porque esta procede de las células foliculares y no del tumor; y como el medular *no depende de la TSH*, la levotiroxina se ajusta a dosis meramente *sustitutiva*, sin suprimir.',
  no:{0:'Es el TERCER tipo histológico en frecuencia, no el segundo: representa alrededor del 3-5% de los cánceres tiroideos.',1:'La tiroglobulina NO sirve como marcador: procede de las células foliculares, no de las parafoliculares.',2:'La TSH no debe suprimirse porque el carcinoma medular no es hormonodependiente: la levotiroxina es solo sustitutiva.'},
  trampa:'Se hace el estudio genético solo si hay antecedentes familiares. Precisamente muchos casos "esporádicos" son los que revelan la mutación.',
  dx:['Carcinoma medular de tiroides','Carcinoma papilar','MEN 2A'],
  obj:'Conocer el manejo del carcinoma medular: estudio de RET, marcadores y dosis de levotiroxina.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías de la American Thyroid Association sobre carcinoma medular.'
},
'MIR-2022-M203': {
  esp:'Medicina Interna', tema:'Endocrinología', sub:'Neoplasia endocrina múltiple tipo 1',
  clave:'Hiperparatiroidismo primario más úlceras pépticas en un joven: MEN 1. Las tres P son paratiroides, páncreas e hipófisis.',
  exp:'Dos piezas encajan de inmediato. La primera es un *hiperparatiroidismo primario*: hipercalcemia de 11,1 con *PTH elevada* de 150 y vitamina D normal, lo que además explica el cólico renal. La segunda son las *úlceras pépticas múltiples* con hemorragia digestiva en un varón de solo *30 años*, que hacen sospechar un *gastrinoma* o síndrome de Zollinger-Ellison. La combinación de ambas en un paciente joven define la *neoplasia endocrina múltiple tipo 1* o síndrome de Wermer, causada por mutaciones del gen supresor *MEN1*, que codifica la menina, con herencia *autosómica dominante*. Se recuerda como las *tres P*: *paratiroides* —el hiperparatiroidismo es la manifestación más frecuente y suele ser la primera, con hiperplasia de las cuatro glándulas—, *páncreas* endocrino —gastrinoma, insulinoma, VIPoma, glucagonoma— e *hipófisis* —prolactinoma sobre todo—. Conviene distinguirla del *MEN 2A*, que combina carcinoma medular de tiroides, feocromocitoma e hiperparatiroidismo, y que se debe a mutaciones de RET.',
  no:{0:'El complejo de Carney asocia mixomas cardiacos, lentiginosis y enfermedad suprarrenal nodular pigmentada, sin gastrinoma.',1:'El síndrome poliglandular tipo 1 asocia candidiasis mucocutánea, hipoparatiroidismo —no hiper— e insuficiencia suprarrenal.',2:'El MEN 2A combina carcinoma medular de tiroides, feocromocitoma e hiperparatiroidismo, y no incluye tumores pancreáticos ni úlceras.'},
  trampa:'Se trata la úlcera y la litiasis por separado. En un paciente de 30 años, esas dos cosas juntas señalan a un síndrome hereditario.',
  dx:['Neoplasia endocrina múltiple tipo 1','Hiperparatiroidismo primario esporádico','MEN 2A','Síndrome de Zollinger-Ellison esporádico'],
  obj:'Reconocer la asociación de hiperparatiroidismo y gastrinoma como MEN 1.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías de la Endocrine Society sobre MEN 1.'
},
'MIR-2022-M52': {
  esp:'Medicina Interna', tema:'Endocrinología', sub:'Antidiabéticos en insuficiencia cardiaca',
  clave:'La PIOGLITAZONA está contraindicada en la insuficiencia cardiaca: retiene sodio y agua y precipita descompensaciones.',
  exp:'La elección del antidiabético en un paciente que acaba de ingresar por *insuficiencia cardiaca* debe hacerse mirando primero qué está *contraindicado*. La *pioglitazona*, una tiazolidindiona, actúa sobre los receptores PPAR-gamma y produce *retención hidrosalina* con expansión de volumen y ganancia de peso, lo que aumenta de forma consistente el riesgo de *hospitalización por insuficiencia cardiaca*; por eso su uso está contraindicado en clase funcional III-IV y desaconsejado en cualquier grado de insuficiencia cardiaca. Las otras tres opciones son seguras y una de ellas es además claramente preferible: la *canagliflozina*, como el resto de inhibidores de SGLT2, no solo es segura sino que *reduce las hospitalizaciones por insuficiencia cardiaca y la mortalidad cardiovascular*, siendo hoy el fármaco de elección en este perfil; el *dulaglutide*, agonista de GLP-1, es seguro y aporta beneficio en enfermedad aterosclerótica; y la *linagliptina* es neutra pero segura, con la particularidad de no requerir ajuste renal. La saxagliptina es la única gliptina con señal de aumento de hospitalizaciones por insuficiencia cardiaca.',
  no:{0:'La linagliptina es neutra en resultados cardiovasculares pero segura, y no requiere ajuste por función renal.',1:'La canagliflozina no solo es segura: reduce las hospitalizaciones por insuficiencia cardiaca y es de elección aquí.',2:'El dulaglutide es seguro y aporta beneficio cardiovascular en enfermedad aterosclerótica.'},
  trampa:'Se piensa solo en la potencia hipoglucemiante. En la insuficiencia cardiaca hay un fármaco que directamente no puede darse.',
  dx:[],
  obj:'Identificar la pioglitazona como contraindicada en la insuficiencia cardiaca.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías ESC sobre diabetes y los estándares de la ADA.'
},
'MIR-2022-M161': {
  esp:'Medicina Interna', tema:'Nutrición', sub:'Desnutrición relacionada con la enfermedad',
  clave:'La obesidad NO excluye la desnutrición: pérdida del 11% del peso en 20 días con ingesta del 25% es desnutrición grave.',
  exp:'Es un error frecuente y peligroso pensar que un paciente con obesidad no puede estar desnutrido. Los criterios *GLIM* combinan un criterio *fenotípico* con uno *etiológico*, y esta paciente cumple ambos con holgura. En lo *fenotípico*: ha perdido *9 kilos* desde el ingreso, es decir, cerca del *11% de su peso en 20 días*, cuando una pérdida superior al 5% en un mes ya define desnutrición y por encima del 10% la califica de *grave*. En lo *etiológico*: hay *reducción de la ingesta* al 25% de lo recomendado, malabsorción por la diarrea, y una *enfermedad aguda con inflamación* —diverticulitis complicada operada, antibioterapia prolongada—, que es el motor catabólico del cuadro. Por eso el diagnóstico es *desnutrición grave relacionada con la enfermedad aguda*. Un índice de masa corporal de 31 no lo desmiente: en la desnutrición del paciente obeso lo que se pierde es *masa magra*, que es la que importa funcionalmente, y su detección tardía empeora el pronóstico, la cicatrización y el riesgo de infección.',
  no:{0:'Perder el 11% del peso en 20 días con ingesta del 25% es, por definición, una alteración grave del estado nutricional.',2:'No hay síndrome de intestino corto: se ha resecado el sigma, no intestino delgado, y la diarrea es probablemente antibiótica.',3:'La obesidad grado II describe el peso, pero no es el problema clínico relevante ni excluye la desnutrición.'},
  trampa:'El índice de masa corporal tranquiliza. Lo que hay que mirar es la pérdida de peso reciente y la ingesta, no el peso absoluto.',
  dx:['Desnutrición grave relacionada con enfermedad aguda','Síndrome de intestino corto','Diarrea por Clostridioides difficile'],
  obj:'Aplicar los criterios GLIM y reconocer la desnutrición en el paciente con obesidad.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios GLIM y guías ESPEN.'
},
'MIR-2022-M174': {
  esp:'Ciencias Básicas', tema:'Metabolismo', sub:'Glucogenosis tipo III',
  clave:'Hepatomegalia con HIPOGLUCEMIA CETÓSICA, miopatía y miocardiopatía, con LACTATO NORMAL: glucogenosis tipo III.',
  exp:'El diagnóstico se construye con cuatro piezas. La *hepatomegalia* y el *retraso del crecimiento* desde la infancia indican una enfermedad de depósito hepático. La *hipoglucemia de 49* con *cetonuria positiva* señala que la cetogénesis funciona correctamente, lo que es decisivo. El *lactato normal* descarta las glucogenosis con bloqueo de la gluconeogénesis, como la tipo I de Von Gierke, en la que el lactato está muy elevado y no hay cetosis prominente. Y la afectación *muscular y cardiaca* —intolerancia al ejercicio de toda la vida, debilidad progresiva, CK de 500 e hipertrofia ventricular izquierda— indica que el defecto afecta también al músculo. Todo ello dibuja una *glucogenosis tipo III* o enfermedad de Cori-Forbes, por déficit de la *enzima desramificante*, que impide degradar completamente el glucógeno más allá de sus ramificaciones. La COVID leve solo actuó como desencadenante que descompensó una enfermedad ya presente. El manejo se basa en comidas frecuentes, almidón de maíz crudo y una dieta rica en proteínas.',
  no:{1:'El síndrome post-COVID no explica la hepatomegalia de cuatro años, la hipoglucemia ni la miocardiopatía.',2:'La TSH de 4,6 es normal: no hay hipertiroidismo.',3:'En los defectos de la beta-oxidación la hipoglucemia es HIPOcetósica, y aquí la cetonuria es claramente positiva.'},
  trampa:'Se atribuye todo a la COVID reciente. Los antecedentes de toda la vida —retraso de crecimiento, intolerancia al ejercicio, hepatomegalia— señalan una enfermedad metabólica de base.',
  dx:['Glucogenosis tipo III','Glucogenosis tipo I','Defecto de la beta-oxidación','Miopatía metabólica'],
  obj:'Diferenciar las glucogenosis por el patrón de lactato y cetosis y la afectación muscular.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Harrison, 21.ª ed., capítulo de errores congénitos del metabolismo.'
},
'MIR-2022-M176': {
  esp:'Medicina Interna', tema:'Nefrología', sub:'Nefropatía diabética incipiente',
  clave:'Microalbuminuria en un diabético: se inicia IECA aunque la tensión sea casi normal. El objetivo es renoprotección, no solo bajar la tensión.',
  exp:'La *microalbuminuria* —una relación albúmina/creatinina entre 30 y 300 mg/g, aquí de *180*— es el marcador más precoz de la *nefropatía diabética* y, además, un potente predictor de riesgo cardiovascular. Su detección obliga a actuar aunque el paciente esté asintomático, y el tratamiento indicado es un *bloqueante del sistema renina-angiotensina*, IECA o ARA-II. La razón es que su beneficio va *más allá del efecto antihipertensivo*: dilatan preferentemente la *arteriola eferente*, con lo que reducen la presión intraglomerular y la hiperfiltración, y eso frena la progresión de la albuminuria y del deterioro renal incluso en pacientes con tensión normal o casi normal, como este, con 137/86. La presencia de *retinopatía proliferativa* refuerza el diagnóstico, porque la afectación microvascular retiniana y renal suelen ir de la mano. Los *antagonistas del calcio* bajan la tensión pero no aportan esa renoprotección específica; y confirmar la albuminuria con una segunda muestra es razonable, pero repetir el estudio no debe retrasar un tratamiento que ya está indicado.',
  no:{0:'La orina de 24 horas ya no es necesaria: el cociente albúmina/creatinina en muestra aislada es el método recomendado.',1:'La ecografía renal no aporta nada en una nefropatía diabética incipiente con retinopatía concordante.',2:'Los antagonistas del calcio reducen la tensión pero no ofrecen la renoprotección específica del bloqueo del eje renina-angiotensina.'},
  trampa:'Se descarta el IECA porque la tensión no es alta. Su indicación aquí es renoprotectora, no antihipertensiva.',
  dx:['Nefropatía diabética incipiente','Nefroangioesclerosis','Glomerulonefritis'],
  obj:'Indicar el bloqueo del eje renina-angiotensina ante microalbuminuria en el diabético.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías KDIGO y los estándares de la ADA.'
},
'MIR-2022-M177': {
  esp:'Medicina Interna', tema:'Nefrología', sub:'Dislipemia del síndrome nefrótico',
  clave:'Colesterol de 500 con HIPOALBUMINEMIA y proteinuria masiva: la dislipemia es SECUNDARIA al síndrome nefrótico.',
  exp:'Las cifras impresionan, pero el resto de la analítica explica su origen sin necesidad de invocar nada genético. La paciente tiene *proteinuria masiva* —cociente albúmina/creatinina de 2.000 mg/g y proteinuria de tres cruces—, *hipoproteinemia* de 5,9 con *albúmina de 3* y *edemas maleolares*: eso es un *síndrome nefrótico*. Y la *hiperlipemia forma parte de su definición*, por dos mecanismos que se suman: el hígado, estimulado por el descenso de la presión oncótica, aumenta la síntesis de lipoproteínas ricas en apoB, y a la vez se pierde por orina la lipoproteín-lipasa y sus cofactores, con lo que el catabolismo de esas partículas disminuye. Dos datos más apoyan que es secundaria: la *ausencia de antecedentes familiares* y, sobre todo, la *ausencia de xantomas y de arco corneal*, que en una hipercolesterolemia familiar con esos niveles y a los 65 años serían casi obligados. El tratamiento pasa por controlar la enfermedad renal de base; el perfil lipídico mejora cuando remite la proteinuria.',
  no:{1:'La heterocigota daría cifras algo menores y, sobre todo, xantomas tendinosos, arco corneal e historia familiar.',2:'La homocigota se manifiesta desde la infancia con xantomas llamativos y enfermedad coronaria muy precoz: no debuta a los 65 años.',3:'La forma recesiva por LDLRAP1 es excepcional, también se manifiesta en la infancia y tampoco cursaría con proteinuria ni hipoalbuminemia.'},
  trampa:'Un colesterol de 500 arrastra hacia lo genético. Antes de etiquetar una dislipemia como primaria hay que descartar las cuatro causas secundarias clásicas: riñón, tiroides, hígado y fármacos.',
  dx:['Dislipemia secundaria a síndrome nefrótico','Hipercolesterolemia familiar','Hipotiroidismo'],
  obj:'Reconocer la hiperlipemia como parte del síndrome nefrótico.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías KDIGO y ESC/EAS sobre dislipemias.'
},

/* ==================== INFECTOLOGÍA ==================== */
'MIR-2022-M164': {
  esp:'Medicina Interna', tema:'Infectología', sub:'Enterobacterias productoras de BLEE',
  clave:'Ante una BLEE el tratamiento de referencia es un CARBAPENÉMICO. En una infección urinaria, el ertapenem basta.',
  exp:'Las *betalactamasas de espectro extendido* son enzimas que hidrolizan penicilinas, cefalosporinas de todas las generaciones y aztreonam, de modo que un aislamiento BLEE deja fuera de juego a la práctica totalidad de los betalactámicos habituales. El tratamiento de referencia son los *carbapenémicos*, que resisten su acción, y entre ellos el *ertapenem* es la elección más adecuada en una infección urinaria o abdominal por enterobacterias: es estable frente a BLEE, se administra en *dosis única diaria* —lo que facilita el tratamiento domiciliario— y, al *no cubrir Pseudomonas ni Acinetobacter*, ejerce menos presión selectiva sobre esos gérmenes que meropenem o imipenem, algo especialmente valioso en un paciente institucionalizado. Sobre los distractores: la *amoxicilina-clavulánico* puede mostrar sensibilidad in vitro pero es poco fiable clínicamente en la infección grave; la *ceftazidima* es una cefalosporina y queda inactivada por definición; y la *tigeciclina* alcanza concentraciones urinarias y séricas bajas, de modo que no es adecuada en bacteriemia ni en infección urinaria.',
  no:{1:'La amoxicilina-clavulánico es poco fiable frente a BLEE en infección grave, aunque el antibiograma sugiera sensibilidad.',2:'La tigeciclina alcanza concentraciones séricas y urinarias bajas: no sirve en bacteriemia ni en infección urinaria.',3:'La ceftazidima es una cefalosporina y queda hidrolizada por la BLEE por definición.'},
  trampa:'Se busca un betalactámico más potente. Frente a una BLEE ninguna cefalosporina sirve: hay que cambiar de familia.',
  dx:['Sepsis urinaria por E. coli BLEE','Sepsis por Pseudomonas','Prostatitis aguda'],
  obj:'Elegir el carbapenémico adecuado ante una enterobacteria productora de BLEE.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías IDSA sobre bacterias multirresistentes.'
},
'MIR-2022-M165': {
  esp:'Medicina Interna', tema:'Infectología', sub:'Profilaxis postexposición al VIH',
  clave:'Carga viral INDETECTABLE mantenida significa INTRANSMISIBLE. No hace falta profilaxis postexposición.',
  exp:'La respuesta se apoya en uno de los hallazgos más importantes de las últimas décadas en VIH, resumido en el lema *indetectable igual a intransmisible*. Los estudios PARTNER y HPTN 052 siguieron a miles de parejas serodiscordantes con relaciones sin preservativo y no documentaron *ninguna* transmisión cuando la persona con VIH mantenía la *carga viral suprimida* de forma estable con tratamiento antirretroviral. Por eso, ante una exposición sexual con una persona en tratamiento y con carga viral indetectable *desde hace años*, el riesgo se considera *insignificante* y *no está indicada la profilaxis postexposición*, que no es inocua: implica 28 días de triple terapia con sus efectos adversos y su coste. La profilaxis sí estaría indicada si la fuente tuviera carga viral detectable o desconocida, y en ese caso debe iniciarse *lo antes posible* y siempre dentro de las *72 horas*, plazo que en este caso todavía no se ha superado. Lo que sí procede es aprovechar la consulta para descartar y prevenir *otras infecciones de transmisión sexual*, que sí se transmiten con independencia de la carga viral, y ofrecer información sobre la profilaxis preexposición.',
  no:{1:'No existe gammaglobulina eficaz frente al VIH: la profilaxis se hace con antirretrovirales.',2:'No está indicada la profilaxis porque el riesgo con carga viral indetectable mantenida es insignificante.',3:'No es tarde: la ventana son 72 horas y han pasado 48. Lo que ocurre es que no está indicada.'},
  trampa:'Se prescribe profilaxis ante cualquier exposición de riesgo. El riesgo depende de la carga viral de la fuente, y aquí es indetectable.',
  dx:[],
  obj:'Aplicar el concepto indetectable igual a intransmisible en la exposición sexual al VIH.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los estudios PARTNER y el documento GeSIDA de profilaxis postexposición.'
},
'MIR-2022-M166': {
  esp:'Medicina Interna', tema:'Infectología', sub:'Meningitis secundaria a otitis',
  clave:'Adulto JOVEN con meningitis tras otitis: neumococo. Ceftriaxona más vancomicina, sin ampicilina porque no hay riesgo de Listeria.',
  exp:'La cobertura empírica de la meningitis bacteriana se construye según *edad y factores de riesgo*, y aquí ambos están definidos. El paciente tiene *34 años*, sin inmunodepresión ni alcoholismo, de modo que *no reúne factores de riesgo para Listeria* —que son la edad superior a 50 años, el embarazo, la inmunodepresión, el alcoholismo o la diabetes—, y por tanto *no hace falta ampicilina*. El foco es una *otitis media* de cinco días de evolución, y el germen que con más frecuencia produce meningitis por contigüidad desde el oído medio es el *Streptococcus pneumoniae*. La combinación indicada es una *cefalosporina de tercera generación* —ceftriaxona o cefotaxima— más *vancomicina*, esta última por si el neumococo tuviera sensibilidad disminuida a cefalosporinas, situación en la que el fallo terapéutico sería catastrófico. Se añade *dexametasona* antes o junto con la primera dosis de antibiótico, que en la meningitis neumocócica reduce las secuelas, sobre todo la sordera. Y hay que valorar además el foco otológico y la posibilidad de mastoiditis.',
  no:{1:'La ampicilina cubre Listeria, innecesaria en un paciente de 34 años sin factores de riesgo, y falta la vancomicina.',2:'El moxifloxacino no es de primera línea en la meningitis bacteriana: se reserva para alergias graves a betalactámicos.',3:'El meropenem es una alternativa en situaciones concretas, pero no es el empírico de elección, y la ampicilina sobra.'},
  trampa:'Se añade ampicilina por rutina. La ampicilina se pone por la LISTERIA, y la Listeria depende de la edad y del estado inmune.',
  dx:['Meningitis neumocócica','Meningitis meningocócica','Absceso cerebral otógeno','Mastoiditis'],
  obj:'Adecuar la cobertura empírica de la meningitis a la edad y al foco.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías IDSA y ESCMID sobre meningitis bacteriana.'
},
'MIR-2022-M168': {
  esp:'Medicina Interna', tema:'Infectología', sub:'Linfogranuloma venéreo',
  clave:'Proctitis por serovar LGV de Chlamydia: doxiciclina 100 mg cada 12 horas durante VEINTIÚN días, no siete.',
  exp:'El *linfogranuloma venéreo* está causado por los serovares *L1, L2 y L3* de *Chlamydia trachomatis*, que a diferencia de los serovares D-K son *invasivos* y afectan al tejido linfático. En hombres que tienen sexo con hombres su presentación más frecuente hoy es la *proctitis*: dolor rectal, tenesmo, secreción mucosa o mucopurulenta, a veces sangrado, con fiebre y *adenopatías inguinales* que pueden fistulizar. Y precisamente porque la infección es *invasiva y linfática*, el tratamiento no es el de una uretritis banal por clamidia: hace falta *doxiciclina 100 mg cada 12 horas durante 21 días*, tres semanas en lugar de los siete días habituales, porque las pautas cortas dejan recidivas. La alternativa en el embarazo o en alergia a tetraciclinas es la azitromicina semanal durante tres semanas. Conviene además tratar a los contactos de los últimos 60 días y descartar otras infecciones de transmisión sexual, muy especialmente el *VIH*, con el que la coinfección es frecuente.',
  no:{1:'La cloxacilina cubre estafilococos y no tiene ninguna actividad frente a Chlamydia.',2:'Esa es la pauta de la gonococia con cobertura de clamidia no invasiva: insuficiente para el linfogranuloma venéreo.',3:'El moxifloxacino tiene actividad frente a Chlamydia, pero no es el tratamiento de elección ni con esa duración.'},
  trampa:'Se aplica la pauta corta de la infección genital por clamidia. El serovar LGV es invasivo y necesita tres semanas.',
  dx:['Linfogranuloma venéreo','Proctitis gonocócica','Herpes anorrectal','Enfermedad inflamatoria intestinal'],
  obj:'Tratar el linfogranuloma venéreo con la duración adecuada de doxiciclina.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con las guías CDC de infecciones de transmisión sexual.'
},
'MIR-2022-M170': {
  esp:'Medicina Interna', tema:'Cardiología', sub:'Endocarditis con insuficiencia cardiaca',
  clave:'Endocarditis con INSUFICIENCIA CARDIACA por destrucción valvular: cirugía urgente. Es la primera indicación quirúrgica.',
  exp:'El paciente tiene una endocarditis por *SARM con sensibilidad intermedia a vancomicina* sobre válvula mitral, y a los siete días de daptomicina aparecen dos hechos que cambian el plan por completo: un *soplo sistólico nuevo 3/6 en ápex irradiado a axila*, que indica *insuficiencia mitral aguda* por destrucción valvular, y un *edema agudo de pulmón* —ortopnea con infiltrado bilateral hiliofugal—. Las indicaciones quirúrgicas en la endocarditis son tres, y la primera y más importante es precisamente esta: la *insuficiencia cardiaca por disfunción valvular*, que es además la que más se beneficia de una intervención *urgente*, porque su mortalidad con tratamiento médico aislado es muy alta. Las otras dos son la *infección no controlada* —persistencia de fiebre y hemocultivos positivos, absceso perianular, germen resistente, que aquí también se cumplen— y la *prevención de embolias* con vegetaciones grandes y episodios embólicos previos. Ajustar el antibiótico o pedir otro ecocardiograma no resolvería una válvula ya destruida, y retrasar la cirugía en este contexto empeora el pronóstico.',
  no:{1:'La ceftarolina puede tener papel en el rescate antibiótico, pero no corrige una válvula destruida ni el edema agudo de pulmón.',2:'La cepa tiene sensibilidad intermedia a vancomicina: volver a ella sería un retroceso terapéutico.',3:'Repetir el ecocardiograma y tratar con diuréticos retrasa la única medida que puede salvar al paciente.'},
  trampa:'Se sigue ajustando el antibiótico ante el fracaso. Cuando aparece insuficiencia cardiaca por destrucción valvular, el tratamiento pasa a ser quirúrgico.',
  dx:['Endocarditis con insuficiencia mitral aguda','Absceso perianular','Embolia séptica'],
  obj:'Reconocer la insuficiencia cardiaca como primera indicación de cirugía urgente en la endocarditis.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías ESC de endocarditis infecciosa.'
},
'MIR-2022-M200': {
  esp:'Medicina Interna', tema:'Infectología', sub:'Escala qSOFA',
  clave:'qSOFA: solo suma la tensión sistólica de 92, que es igual o menor de 100. Un punto.',
  exp:'La escala *qSOFA* se diseñó para identificar rápidamente, y sin analítica, a los pacientes con infección que tienen mayor riesgo de mala evolución. Consta de *tres criterios*, cada uno de un punto: *alteración del nivel de conciencia*, definida como Glasgow menor de 15; *frecuencia respiratoria igual o mayor de 22*; y *presión arterial sistólica igual o menor de 100 mmHg*. Aplicándola a este paciente: el *Glasgow es de 15*, es decir, normal, y no suma; la *frecuencia respiratoria es de 18*, por debajo de 22, y tampoco suma; y la *presión sistólica es de 92*, que sí cumple el umbral y suma *un punto*. Conviene fijarse en lo que *no* entra en la escala, porque es la trampa: la *frecuencia cardiaca de 110* y la *temperatura de 38* no forman parte del qSOFA, aunque sí de los antiguos criterios de síndrome de respuesta inflamatoria sistémica. La interpretación es que *dos o más puntos* identifican a un paciente de alto riesgo que debe ser evaluado con urgencia; con un punto no puede descartarse la gravedad, de modo que la escala orienta pero nunca sustituye al juicio clínico.',
  no:{1:'Para dos puntos haría falta cumplir otro criterio, y ni el Glasgow ni la frecuencia respiratoria lo cumplen.',2:'Tres puntos exigirían cumplir los tres criterios de la escala.',3:'La escala solo tiene tres criterios: cuatro puntos es imposible.'},
  trampa:'Se cuentan la fiebre y la taquicardia. Esos son criterios de respuesta inflamatoria sistémica, no del qSOFA.',
  dx:[],
  obj:'Calcular correctamente el qSOFA y conocer sus tres criterios.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con las definiciones Sepsis-3.'
},
'MIR-2022-M84': {
  esp:'Pediatría', tema:'Infectología pediátrica', sub:'Mononucleosis infecciosa',
  clave:'Faringoamigdalitis con membranas, adenopatías en MÚLTIPLES territorios y ESPLENOMEGALIA: mononucleosis por Epstein-Barr.',
  exp:'El cuadro reúne los rasgos que separan la mononucleosis de una amigdalitis estreptocócica corriente. La *faringoamigdalitis* es exudativa y con membranas, lo que por sí solo no discrimina; pero se acompaña de *astenia intensa y desproporcionada*, que es su síntoma más característico y el que más tarda en resolverse; de *adenopatías en muchos territorios* —cervicales anteriores y *posteriores*, occipitales y *epitrocleares*, siendo estas dos últimas localizaciones muy sugestivas—; y sobre todo de *esplenomegalia*, presente en cerca de la mitad de los casos, junto con hepatomegalia. La serología a solicitar es la de *virus de Epstein-Barr*: anticuerpos heterófilos, el test de Paul-Bunnell o Monospot, e IgM frente al antígeno de la cápside vírica. Dos advertencias prácticas: si se administran *aminopenicilinas* aparece un exantema maculopapuloso en la gran mayoría de los pacientes, lo que no es una alergia verdadera; y hay que *desaconsejar los deportes de contacto* durante varias semanas por el riesgo de *rotura esplénica*.',
  no:{0:'El sarampión cursa con catarro, conjuntivitis, manchas de Koplik y exantema descendente, no con esplenomegalia y adenopatías epitrocleares.',1:'La rubeola da un cuadro leve con adenopatías retroauriculares y exantema, sin este grado de astenia ni membranas amigdalares.',3:'El parvovirus B19 produce el eritema infeccioso con las mejillas abofeteadas, sin faringoamigdalitis exudativa ni esplenomegalia.'},
  trampa:'Se trata como una amigdalitis bacteriana con amoxicilina. Además de ser inútil, provoca un exantema alarmante que se confunde con alergia.',
  dx:['Mononucleosis infecciosa','Faringoamigdalitis estreptocócica','Infección aguda por citomegalovirus','Toxoplasmosis'],
  obj:'Reconocer la mononucleosis infecciosa por sus adenopatías y la esplenomegalia.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Nelson, Tratado de Pediatría.'
},
'MIR-2022-M79': {
  esp:'Pediatría', tema:'Infectología pediátrica', sub:'Exantema súbito',
  clave:'Fiebre alta tres días en un lactante con buen estado, y cuando la fiebre DESAPARECE aparece el exantema: exantema súbito.',
  exp:'La cronología es la firma del diagnóstico y hay que retenerla: en el *exantema súbito* o *roséola infantil*, causado por el *herpesvirus humano tipo 6*, el niño presenta *tres o cuatro días de fiebre alta*, a menudo por encima de 39 o 40 grados, con un estado general sorprendentemente *conservado* salvo irritabilidad y con una exploración prácticamente normal; y el *exantema maculopapuloso* rosado aparece justo *cuando la fiebre cede*, extendiéndose desde el tronco a la cara y las extremidades, sin descamación y desapareciendo en pocos días. Es la causa más frecuente de exantema febril en el *lactante* entre los 6 y los 24 meses, y también una causa muy frecuente de *crisis febriles* por la altura de la fiebre. El contraste con las demás enfermedades exantemáticas está en esa secuencia: en el *sarampión* el exantema aparece *con* la fiebre en su punto máximo, y el niño está claramente enfermo, con catarro, conjuntivitis y manchas de Koplik. El tratamiento es solo sintomático.',
  no:{0:'El eritema infeccioso empieza con las mejillas abofeteadas y sigue con un exantema reticulado, sin fiebre alta previa de tres días.',1:'En el sarampión el exantema coincide con el pico febril y el niño está muy afectado, con catarro, conjuntivitis y Koplik.',3:'La escarlatina da un exantema áspero en piel de gallina con lengua aframbuesada y faringitis estreptocócica, y la fiebre no desaparece al brotar.'},
  trampa:'Se busca una causa grave por la fiebre de 40 grados. Un lactante con fiebre alta, buen estado y exploración normal que brota al bajar la fiebre es una roséola.',
  dx:['Exantema súbito','Sarampión','Escarlatina','Reacción medicamentosa'],
  obj:'Reconocer la secuencia fiebre-defervescencia-exantema del exantema súbito.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Nelson, Tratado de Pediatría.'
},
'MIR-2022-M77': {
  esp:'Pediatría', tema:'Neumología pediátrica', sub:'Empiema tabicado',
  clave:'Empiema con MÚLTIPLES TABIQUES: tubo de drenaje MÁS fibrinolíticos intrapleurales. La cirugía queda para el fracaso.',
  exp:'El niño tiene un *empiema paraneumónico* confirmado por dos datos: el líquido extraído es *purulento* y la ecografía muestra *múltiples tabiques*, es decir, el derrame ya está *organizándose* en compartimentos. Ese detalle condiciona el tratamiento, porque un derrame tabicado *no se vacía* con un simple drenaje: los tabiques de fibrina crean bolsas independientes que el tubo no alcanza. Por eso la conducta indicada es colocar un *tubo de tórax* y añadir *fibrinolíticos intrapleurales* —uroquinasa o alteplasa—, que rompen esos tabiques y permiten evacuar el pus; esta combinación es en la infancia tan eficaz como la cirugía y mucho menos agresiva. La *toracoscopia videoasistida* con desbridamiento, o en última instancia la *decorticación*, quedan para el fracaso de esta estrategia. Las toracocentesis repetidas son insuficientes y traumatizantes, y ampliar el antibiótico no sirve de nada cuando el problema es *mecánico*: el pus a presión y tabicado no se cura sin drenarlo.',
  no:{1:'Las toracocentesis repetidas no vacían un derrame tabicado y someten al niño a punciones sucesivas.',2:'La decorticación quirúrgica es un segundo escalón, para cuando fracasan el drenaje y los fibrinolíticos.',3:'Ampliar el antibiótico no resuelve un problema mecánico: el pus tabicado hay que evacuarlo.'},
  trampa:'Se cambia el antibiótico ante la fiebre persistente. La fiebre persiste porque hay pus encapsulado, y eso se drena.',
  dx:['Empiema pleural tabicado','Derrame paraneumónico simple','Absceso pulmonar'],
  obj:'Tratar el empiema tabicado con drenaje y fibrinolíticos intrapleurales.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías BTS sobre infección pleural en la infancia.'
},

/* ==================== REUMATOLOGÍA Y NEUROLOGÍA ==================== */
'MIR-2022-M171': {
  esp:'Medicina Interna', tema:'Reumatología', sub:'Dermatomiositis anti-MDA5',
  clave:'Úlceras en manos con enfermedad intersticial rápidamente progresiva y fuerza NORMAL: dermatomiositis anti-MDA5.',
  exp:'El caso describe un fenotipo muy concreto dentro de las miopatías inflamatorias. Hay *lesiones cutáneas ulcerosas* en palmas y dedos, que son el rasgo característico del anticuerpo *anti-MDA5* y traducen una vasculopatía cutánea. Hay *enfermedad pulmonar intersticial de curso rápido* —dos meses de disnea progresiva, crepitantes bibasales, patrón intersticial y saturación del 93%—, que es la manifestación dominante y la que marca el pronóstico, con formas rápidamente progresivas de mortalidad muy alta. Y hay una disociación llamativa: la *fuerza muscular es normal* y las enzimas están solo *ligeramente elevadas*, pese a que la biopsia muestra los hallazgos típicos de dermatomiositis —*atrofia perifascicular* e infiltrados *perivasculares*—; ese patrón se denomina dermatomiositis *amiopática o hipomiopática* y es característico del anti-MDA5. Reconocerlo importa porque obliga a un tratamiento inmunosupresor agresivo y precoz. Conviene recordar los otros anticuerpos: el *anti-TIF1-gamma* se asocia a *neoplasia oculta* en el adulto, el *anti-Jo1* al síndrome antisintetasa con manos de mecánico y artritis, y el *anti-Mi2* a la dermatomiositis clásica con buena respuesta al tratamiento.',
  no:{0:'El anti-TIF1-gamma se asocia a dermatomiositis paraneoplásica y a afectación cutánea extensa, no a este perfil de úlceras con intersticial rápida.',1:'El anti-FHL-1 es un anticuerpo de descripción reciente sin este fenotipo característico.',3:'Las miopatías miofibrilares son enfermedades degenerativas hereditarias, sin lesiones cutáneas ni infiltrados inflamatorios perivasculares.'},
  trampa:'Se descarta la dermatomiositis porque la fuerza es normal. La forma amiopática existe, y es precisamente la que peor pulmón tiene.',
  dx:['Dermatomiositis anti-MDA5','Síndrome antisintetasa','Dermatomiositis paraneoplásica','Fibrosis pulmonar idiopática'],
  obj:'Reconocer el fenotipo de la dermatomiositis anti-MDA5 con enfermedad intersticial rápida.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con revisiones sobre autoanticuerpos específicos de miositis.'
},
'MIR-2022-M172': {
  esp:'Medicina Interna', tema:'Reumatología', sub:'Fiebre mediterránea familiar',
  clave:'Fiebre recurrente desde la infancia con SEROSITIS y lesiones ERISIPELOIDES en las piernas: fiebre mediterránea familiar.',
  exp:'Los síndromes autoinflamatorios se distinguen por la *duración de los episodios* y por sus *manifestaciones acompañantes*. La *fiebre mediterránea familiar* se caracteriza por brotes *cortos*, de uno a tres días, de fiebre alta acompañada de *serositis*: peritonitis —el dolor abdominal difuso con defensa, que explica la apendicectomía en blanco de la infancia, un dato clásico—, pleuritis y artritis. Su lesión cutánea distintiva es el *eritema erisipeloide* en la cara anterolateral y distal de las piernas y en el dorso del pie, exactamente como aquí. Es una enfermedad *autosómica recesiva* por mutaciones del gen *MEFV*, que codifica la pirina, prevalente en poblaciones mediterráneas. Su importancia va más allá de los brotes: la inflamación repetida puede llevar a *amiloidosis AA* con insuficiencia renal, y por eso el tratamiento con *colchicina* de forma continua no solo previene los episodios sino también esa complicación. Los otros síndromes tienen firmas distintas: el *Muckle-Wells* asocia urticaria y sordera neurosensorial, el *TRAPS* da brotes largos de más de una semana con mialgia migratoria, y el *Blau* cursa con artritis, uveítis y exantema granulomatoso.',
  no:{0:'El Muckle-Wells cursa con exantema urticariforme y sordera neurosensorial progresiva, ausentes aquí.',2:'El síndrome de Blau asocia artritis granulomatosa, uveítis y dermatitis, no serositis recurrente.',3:'El TRAPS produce brotes PROLONGADOS, de una a tres semanas, con mialgia migratoria y edema periorbitario.'},
  trampa:'Se busca una causa infecciosa o una enfermedad inflamatoria intestinal. La clave es que los episodios son estereotipados, cortos y se normalizan por completo entre brotes.',
  dx:['Fiebre mediterránea familiar','Síndrome TRAPS','Enfermedad de Crohn','Porfiria aguda'],
  obj:'Diferenciar los síndromes autoinflamatorios por la duración de los brotes y sus manifestaciones.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios de Tel-Hashomer y guías EULAR.'
},
'MIR-2022-M175': {
  esp:'Medicina Interna', tema:'Reumatología', sub:'Autoanticuerpos en esclerodermia',
  clave:'En esclerodermia, el anti-ARN polimerasa III marca el riesgo de CRISIS RENAL: por eso es esencial en el seguimiento.',
  exp:'La paciente tiene una *esclerosis sistémica* incipiente: *fenómeno de Raynaud* de cuatro años, *reflujo* por afectación esofágica y *esclerodactilia*, esa dificultad para pinzar la piel del dorso de las manos que es el signo cutáneo precoz. La pregunta no busca el anticuerpo más frecuente sino el que tiene mayores *consecuencias pronósticas*, y ese es el *anti-ARN polimerasa III*: se asocia a la forma *difusa* con progresión cutánea rápida y, sobre todo, al mayor riesgo de *crisis renal esclerodérmica*, una urgencia con hipertensión maligna y fracaso renal agudo. Su positividad obliga a *vigilar la tensión arterial de forma estrecha y periódica*, a extremar la prudencia con los corticoides —que la precipitan— y a instruir a la paciente para que consulte de inmediato ante cefalea o cifras altas, además de asociarse a un riesgo aumentado de neoplasia. Conviene tener el mapa completo: los *anticentrómero* marcan la forma limitada y el riesgo de *hipertensión pulmonar*, y los *anti-Scl-70* la forma difusa con *enfermedad pulmonar intersticial*.',
  no:{0:'Los anti-ADN pertenecen al lupus y se correlacionan con la nefritis lúpica, no con la esclerodermia.',1:'Los anti-proteinasa 3 corresponden a la granulomatosis con poliangeítis.',2:'Los anti-membrana basal glomerular definen el síndrome de Goodpasture.'},
  trampa:'Se busca el anticuerpo más habitual de la enfermedad. La pregunta pide el que cambia el seguimiento, y ese es el que anticipa la crisis renal.',
  dx:['Esclerosis sistémica','Fenómeno de Raynaud primario','Lupus'],
  obj:'Asociar cada autoanticuerpo de la esclerodermia con su complicación característica.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con recomendaciones EULAR sobre esclerosis sistémica.'
},
'MIR-2022-M179': {
  esp:'Medicina Interna', tema:'Reumatología', sub:'Lupus inducido por fármacos',
  clave:'Lupus inducido por fármacos: el anticuerpo característico es el ANTIHISTONA, positivo en más del 90%.',
  exp:'El *lupus inducido por fármacos* se sospecha cuando aparecen manifestaciones lúpicas tras iniciar un medicamento, y los clásicos son la *hidralazina*, la *procainamida*, la isoniacida, la quinidina, la minociclina, el metildopa y los *anti-TNF*. Su perfil serológico tiene dos rasgos: los *ANA son positivos*, como en el lupus idiopático, y los *anticuerpos antihistona* aparecen en más del *90%* de los casos, lo que los convierte en el marcador que hay que solicitar. Igual de importante es lo que *no* suele encontrarse: los *anti-ADN nativo* y los *anti-Sm* son característicamente *negativos*, y el complemento *no se consume*. También el cuadro clínico es más benigno que el del lupus idiopático: predominan las manifestaciones cutáneas, las artralgias, la fiebre y la serositis, mientras que la afectación *renal y del sistema nervioso central son raras*. Y lo esencial del manejo es que *retirar el fármaco* suele bastar, con resolución en semanas o meses, aunque los anticuerpos puedan persistir más tiempo.',
  no:{1:'Los ANCA se asocian a las vasculitis, aunque algunos fármacos como el propiltiouracilo pueden inducir vasculitis ANCA: no es el marcador de este cuadro.',2:'Los anticromatina se solapan con los antihistona pero no son el marcador clásico que se solicita.',3:'Los antifosfolípidos se relacionan con trombosis y morbilidad obstétrica, no con el lupus farmacológico.'},
  trampa:'Se piden anti-ADN por reflejo ante cualquier sospecha de lupus. En el inducido por fármacos suelen ser negativos: el marcador es el antihistona.',
  dx:['Lupus inducido por fármacos','Lupus eritematoso sistémico','Toxicodermia'],
  obj:'Reconocer el perfil serológico del lupus inducido por fármacos.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Harrison, 21.ª ed.'
},
'MIR-2022-M205': {
  esp:'Medicina Interna', tema:'Reumatología', sub:'Artritis psoriásica',
  clave:'Oligoartritis ASIMÉTRICA con afectación de INTERFALÁNGICAS y lesiones descamativas en codos y rodillas: artritis psoriásica.',
  exp:'Tres datos separan este cuadro de una artritis reumatoide. El primero es el *patrón articular*: la afectación es *asimétrica* —dos metacarpofalángicas de la mano derecha y dos interfalángicas de la izquierda— y *oligoarticular*, mientras que la artritis reumatoide es característicamente *simétrica y poliarticular*. El segundo es qué articulaciones se afectan: la implicación de las *interfalángicas*, sobre todo distales, es muy propia de la artritis psoriásica y en cambio *respetada* por la artritis reumatoide. El tercero es la *piel*: las lesiones *descamativas en superficies extensoras* de codos y rodillas son psoriasis en placas, aunque el paciente no lo sepa, motivo por el cual hay que explorar siempre codos, rodillas, cuero cabelludo, ombligo, pliegue interglúteo y uñas ante una artritis inflamatoria. Se suma un dato serológico coherente: el *factor reumatoide y los anti-CCP son negativos*, lo que sitúa el cuadro entre las *espondiloartritis seronegativas*. La radiografía sin erosiones indica una fase precoz, y lo que procede es iniciar tratamiento antes de que aparezca daño estructural.',
  no:{0:'La artritis reumatoide es simétrica, poliarticular, respeta las interfalángicas distales y suele ser seropositiva.',1:'El lupus produce artritis no erosiva y no deformante, sin lesiones psoriásicas en superficies extensoras.',3:'La artrosis no cursa con VSG y PCR elevadas ni con inflamación de metacarpofalángicas en un varón de 35 años.'},
  trampa:'Se piensa en artritis reumatoide ante cualquier artritis de manos. Basta con mirar los codos y las rodillas para cambiar el diagnóstico.',
  dx:['Artritis psoriásica','Artritis reumatoide seronegativa','Artritis reactiva','Gota'],
  obj:'Diferenciar la artritis psoriásica de la artritis reumatoide por el patrón articular y la piel.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios CASPAR.'
},
'MIR-2022-M202': {
  esp:'Medicina Interna', tema:'Nefrología', sub:'Glomerulonefritis pauciinmune',
  clave:'Semilunas en el 80% de los glomérulos con INMUNOFLUORESCENCIA NEGATIVA y ANCA positivos: vasculitis pauciinmunitaria.',
  exp:'Las glomerulonefritis rápidamente progresivas se clasifican en *tres tipos* según el patrón de la *inmunofluorescencia*, y ese es exactamente el razonamiento que pide la pregunta. El *tipo I* muestra un depósito *lineal* de IgG a lo largo de la membrana basal y corresponde a la enfermedad por *anticuerpos anti-MBG* o síndrome de Goodpasture. El *tipo II* muestra depósitos *granulares* de inmunoglobulinas y complemento, y agrupa a la glomerulonefritis postinfecciosa, la nefropatía IgA, la nefritis lúpica y la membranoproliferativa. Y el *tipo III* es *pauciinmune*: la inmunofluorescencia es *negativa o casi negativa* para todas las inmunoglobulinas y el complemento, precisamente lo que describe el enunciado, y se asocia a los *ANCA*, que aquí son positivos, y a las vasculitis de pequeño vaso. Es el tipo *más frecuente* en el adulto mayor. El tratamiento no admite demora: corticoides a dosis altas con ciclofosfamida o rituximab, y plasmaféresis en las formas con creatinina muy elevada o hemorragia alveolar.',
  no:{0:'La postinfecciosa mostraría depósitos GRANULARES de C3 e IgG, no una inmunofluorescencia negativa.',2:'La nefropatía IgA mostraría depósitos mesangiales de IgA, que aquí son expresamente negativos.',3:'El Goodpasture daría un depósito LINEAL de IgG y anticuerpos anti-MBG positivos, que aquí son negativos.'},
  trampa:'Se elige por la clínica sin usar la inmunofluorescencia. Es justamente ella la que clasifica las glomerulonefritis con semilunas en sus tres tipos.',
  dx:['Vasculitis pauciinmune ANCA','Enfermedad por anti-MBG','Nefritis lúpica','Nefropatía IgA'],
  obj:'Clasificar las glomerulonefritis rápidamente progresivas por el patrón de inmunofluorescencia.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías KDIGO de glomerulonefritis.'
},
'MIR-2022-M149': {
  esp:'Medicina Interna', tema:'Neurología', sub:'Degeneración combinada subaguda',
  clave:'Macrocitosis de 120, tez amarillenta y pérdida de sensibilidad VIBRATORIA y POSICIONAL: déficit de B12 con mielosis funicular.',
  exp:'Los tres hallazgos apuntan al mismo sitio. El *VCM de 120 con anisocitosis* indica una anemia *macrocítica megaloblástica*. La *tez amarillenta* no es una ictericia hepática sino el color pajizo característico del déficit de B12, mezcla de palidez por la anemia y de un tinte subictérico por la *eritropoyesis ineficaz*, es decir, la destrucción intramedular de precursores, que también eleva la LDH. Y la exploración neurológica muestra la afectación de los *cordones posteriores*: pérdida de la sensibilidad *vibratoria y posicional* en zonas distales, junto con las parestesias en manos y pies. Ese conjunto define la *mielosis funicular* o *degeneración combinada subaguda* de la médula, que además afecta a la vía piramidal, produciendo con el tiempo reflejos exaltados y Babinski. Es esencial reconocerla pronto porque el daño neurológico *se hace irreversible* si el tratamiento se retrasa, y porque puede aparecer *sin anemia*. Hay que medir B12, y si el nivel es limítrofe, homocisteína y ácido metilmalónico; el tratamiento es B12 parenteral, buscando después la causa: anemia perniciosa, gastritis atrófica, cirugía gástrica, veganismo estricto o metformina.',
  no:{0:'La mielopatía cervicoartrósica no produce macrocitosis ni tez amarillenta, y cursa con signos de compresión medular y dolor cervical.',1:'La mielitis necrosante subaguda es una entidad rara y de curso rápido, sin alteración hematológica.',3:'La esclerosis múltiple daría brotes con lesiones diseminadas en tiempo y espacio, no una macrocitosis de 120.'},
  trampa:'Se separan la anemia y los síntomas neurológicos como si fueran dos problemas. Una sola vitamina los explica a los dos.',
  dx:['Degeneración combinada subaguda por déficit de B12','Mielopatía cervicoartrósica','Esclerosis múltiple','Polineuropatía diabética'],
  obj:'Relacionar la macrocitosis con la afectación de cordones posteriores en el déficit de B12.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Harrison, 21.ª ed.'
},
'MIR-2022-M97': {
  esp:'Medicina Interna', tema:'Neurología', sub:'Encefalitis autoinmune',
  clave:'Psicosis, discinesias ORALES y crisis en un joven: encefalitis anti-receptor NMDA. Se buscan autoanticuerpos en LCR y suero.',
  exp:'La secuencia del cuadro es tan característica que permite el diagnóstico casi sin pruebas. Comienza con un *pródromo psiquiátrico* —alucinaciones, alteraciones conductuales, catatonía— que lleva a estos pacientes a psiquiatría, y en pocos días se le añaden *déficit de memoria*, *movimientos anormales* con las típicas *discinesias orofaciales*, y después *crisis convulsivas*, disautonomía e hipoventilación. Eso es una *encefalitis autoinmune por anticuerpos contra el receptor NMDA*, la más frecuente de las encefalitis autoinmunes, propia de gente *joven* y con predominio en mujeres, en las que se asocia con frecuencia a un *teratoma de ovario* que hay que buscar activamente. El diagnóstico se hace *detectando los autoanticuerpos en líquido cefalorraquídeo y suero*, siendo el líquido más sensible y específico. Las otras pruebas ayudan pero no diagnostican: la resonancia es *normal* en más de la mitad de los casos y el electroencefalograma muestra hallazgos inespecíficos, aunque el patrón de *delta brush extremo* es sugestivo. Y dar corticoides "a ver qué pasa" no es un método diagnóstico. El tratamiento combina inmunoterapia y la extirpación del tumor si existe.',
  no:{0:'La resonancia es normal en más de la mitad de los casos: no descarta ni confirma el diagnóstico.',1:'El vídeo-EEG documenta las crisis pero no aporta la etiología, que es lo que se busca.',2:'Tratar a ciegas para ver la respuesta no es un procedimiento diagnóstico y retrasa la confirmación.'},
  trampa:'Se etiqueta de brote psicótico y se remite a psiquiatría. La aparición de discinesias orales y crisis en días obliga a pensar en encefalitis autoinmune.',
  dx:['Encefalitis anti-receptor NMDA','Encefalitis herpética','Brote psicótico','Encefalopatía tóxica'],
  obj:'Sospechar la encefalitis anti-NMDA y confirmarla con autoanticuerpos en LCR.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios de Graus sobre encefalitis autoinmune.'
},
'MIR-2022-M67': {
  esp:'Medicina Interna', tema:'Otorrinolaringología', sub:'Enfermedad de Ménière',
  clave:'Crisis de vértigo de MINUTOS A HORAS con hipoacusia, acúfeno y plenitud ótica: enfermedad de Ménière.',
  exp:'La *duración* de la crisis y la presencia de *síntomas cocleares* son los dos ejes que ordenan el diagnóstico diferencial del vértigo periférico. En la *enfermedad de Ménière*, causada por un hidrops endolinfático, las crisis duran de *veinte minutos a varias horas*, son *recurrentes*, y se acompañan de la tríada coclear: *hipoacusia* fluctuante de predominio en frecuencias graves, *acúfeno* y *sensación de plenitud ótica*, todos en el mismo oído. El caso lo cumple entero. La exploración es coherente con un déficit vestibular *periférico derecho*: *nistagmo horizonte-rotatorio* que bate hacia el lado *sano*, es decir, a la izquierda, y *Romberg* y *Unterberger* con desviación hacia el lado *enfermo*, el derecho. El contraste con las alternativas es claro: el *vértigo posicional* dura *segundos* y se desencadena con la postura, sin síntomas cocleares; la *neuronitis vestibular* dura *días* de forma continua y tampoco afecta a la audición; y el *Ramsay-Hunt* añadiría vesículas en el conducto auditivo y parálisis facial.',
  no:{0:'El vértigo posicional dura segundos, se desencadena con los movimientos de la cabeza y no cursa con hipoacusia ni acúfeno.',1:'La neuronitis vestibular produce vértigo continuo de días y NO afecta a la audición.',3:'El Ramsay-Hunt asocia vesículas en el conducto auditivo externo, otalgia intensa y parálisis facial.'},
  trampa:'Se atiende solo al vértigo. Los síntomas del oído —acúfeno, hipoacusia y plenitud— son los que dan el diagnóstico.',
  dx:['Enfermedad de Ménière','Vértigo posicional paroxístico benigno','Neuronitis vestibular','Neurinoma del acústico'],
  obj:'Diferenciar los vértigos periféricos por duración de la crisis y síntomas cocleares.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con los criterios de la Bárány Society.'
},
'MIR-2022-M59': {
  esp:'Medicina Interna', tema:'Oftalmología', sub:'Retinosis pigmentaria',
  clave:'Ceguera NOCTURNA con visión central conservada en un joven: retinosis pigmentaria. Fallan primero los BASTONES.',
  exp:'El síntoma inicial señala la célula afectada. Los *bastones* son los fotorreceptores responsables de la visión en *baja luminosidad* y de la *visión periférica*, y se distribuyen sobre todo en la retina periférica; los *conos* se concentran en la mácula y sostienen la *visión central*, el detalle y el color. Este paciente refiere *ceguera nocturna* y mala adaptación a la oscuridad, con tropiezos en escaleras y bordillos —es decir, pérdida de *campo periférico*— mientras *conserva la lectura y la televisión*, o sea, la visión central. Ese patrón es el de una *degeneración primaria de bastones*, y en un varón joven corresponde a una *retinosis pigmentaria*, un grupo de distrofias hereditarias que evolucionan hacia una *visión en cañón de escopeta* por reducción progresiva del campo. En el fondo de ojo se ven los *espículas óseas* pigmentarias en la periferia, con atenuación arteriolar y palidez papilar cérea, y el electrorretinograma está abolido. El contraste con las distrofias *maculares* —Stargardt y Best— es total: en ellas se pierde primero la *visión central*, con dificultad para leer, y se conserva la periférica.',
  no:{0:'La enfermedad de Stargardt es una distrofia MACULAR: la pérdida es de visión central, con dificultad para leer.',1:'La distrofia viteliforme de Best también es macular y afecta a la visión central.',3:'El desprendimiento de retina se instaura de forma brusca, con miodesopsias, fotopsias y una sombra que avanza, no en meses.'},
  trampa:'Se piensa en un problema de la mácula porque es lo más habitual. Aquí la visión central está intacta: el problema está en la periferia.',
  dx:['Retinosis pigmentaria','Enfermedad de Stargardt','Déficit de vitamina A','Glaucoma avanzado'],
  obj:'Localizar la lesión retiniana según el patrón de pérdida visual.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con la Academia Americana de Oftalmología.'
},
'MIR-2022-M152': {
  esp:'Medicina Familiar', tema:'Geriatría', sub:'Cribado de sarcopenia',
  clave:'Sin medir masa muscular no se CONFIRMA la sarcopenia. Un Timed Up and Go de 26 segundos indica que, de haberla, sería GRAVE.',
  exp:'El algoritmo *EWGSOP2* ordena el diagnóstico de sarcopenia en tres pasos y hay que respetarlos. Primero se *sospecha* con un cribado, y una prueba de *levantarse de la silla cinco veces* que tarda más de 15 segundos —aquí *20*— indica *fuerza baja*, es decir, sarcopenia *probable*. Segundo, se *confirma* demostrando una *masa muscular reducida* mediante densitometría, bioimpedancia o imagen; ese paso *no se ha realizado*, de modo que la sarcopenia no puede darse por confirmada. Y tercero, se *gradúa la gravedad* según el *rendimiento físico*: un *Timed Up and Go igual o superior a 20 segundos* —aquí *26*— indica rendimiento bajo y, en caso de confirmarse la sarcopenia, la calificaría de *grave*. Por eso la afirmación correcta es condicional: si la tuviera, sería grave. Y hay un dato adicional muy relevante para la práctica: un TUG por encima de *13,5 segundos* es un marcador establecido de *alto riesgo de caídas*, de modo que esta paciente de 79 años que vive sola necesita una intervención inmediata sobre ese riesgo, con ejercicio de resistencia, aporte proteico adecuado, revisión de fármacos y adaptación del domicilio.',
  no:{0:'Un Timed Up and Go de 26 segundos indica alto riesgo de caídas: el umbral de alarma está en torno a 13,5 segundos.',1:'No puede confirmarse sin medir la masa muscular, que es el segundo paso del algoritmo y no se ha realizado.',3:'Sí se sospecha: la prueba de la silla alterada define sarcopenia probable.'},
  trampa:'Se afirma o se niega el diagnóstico sin completar el algoritmo. Fuerza baja da la sospecha; masa baja confirma; rendimiento bajo gradúa.',
  dx:['Sarcopenia probable','Fragilidad','Artrosis limitante'],
  obj:'Aplicar el algoritmo EWGSOP2 de cribado, confirmación y gradación de la sarcopenia.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con el consenso EWGSOP2.'
},

/* ==================== BIOÉTICA, PREVENCIÓN Y CLÍNICA GENERAL ==================== */
'MIR-2022-M181': {
  esp:'Bioética', tema:'Autonomía del paciente', sub:'Rechazo de tratamiento',
  clave:'Es el PACIENTE capaz quien pide retirar un tratamiento que ya recibe: eso es RECHAZO DE TRATAMIENTO, un derecho reconocido.',
  exp:'Hay que distinguir con precisión cuatro conceptos que se confunden constantemente. El *rechazo de tratamiento* es la decisión del *propio paciente*, capaz e informado, de *no iniciar o de retirar* una medida terapéutica, aunque de ello se siga la muerte; es un derecho reconocido por la Ley 41/2002 y una expresión directa del principio de *autonomía*, y el médico está obligado a respetarlo. La *limitación o adecuación del esfuerzo terapéutico* es distinta: la decide el *equipo médico* cuando una intervención resulta desproporcionada o fútil. La *obstinación terapéutica* es lo contrario, mantener tratamientos que ya no aportan beneficio. Y la *eutanasia* requiere una *acción deliberada* que causa la muerte, no la simple retirada de un soporte. Este caso es claramente el primero: es *el paciente*, capaz y con sufrimiento intolerable, quien solicita de forma reiterada y confirmada que se retire la ventilación no invasiva, con apoyo de su familia. Lo que corresponde es respetar su voluntad, dejarlo documentado en la historia y garantizar una *sedación paliativa* adecuada para que la retirada no le suponga sufrimiento.',
  no:{1:'La limitación del esfuerzo terapéutico la decide el equipo médico por futilidad, no el paciente por su voluntad.',2:'La obstinación terapéutica es justo lo contrario: mantener medidas que no aportan beneficio.',3:'La eutanasia exige una acción deliberada dirigida a causar la muerte; retirar un soporte que el paciente rechaza no lo es.'},
  trampa:'Se confunde retirar un soporte a petición del paciente con eutanasia. La diferencia está en quién decide y en si se actúa o se cesa de intervenir.',
  dx:[],
  obj:'Distinguir rechazo de tratamiento, limitación del esfuerzo terapéutico y eutanasia.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con la Ley 41/2002 y guías SECPAL.'
},
'MIR-2022-M183': {
  esp:'Bioética', tema:'Final de la vida', sub:'Limitación del esfuerzo terapéutico',
  clave:'Aquí decide el EQUIPO MÉDICO por desproporción de la medida: limitación o adecuación del esfuerzo terapéutico.',
  exp:'El contraste con el caso anterior es exactamente lo que hay que aprender. Aquí la paciente tiene una *demencia avanzada* de ocho años, con deterioro cognitivo grave y dependencia total, y *no puede expresar su voluntad*: no es ella quien rechaza nada. Es el *médico responsable* quien, valorando el balance entre beneficio y carga, propone *no iniciar* la alimentación enteral por sonda. Eso es una *limitación o adecuación del esfuerzo terapéutico*, y está bien fundamentada, porque la evidencia demuestra que en la demencia avanzada la sonda de alimentación *no prolonga la supervivencia, no previene las aspiraciones —que son sobre todo de saliva y de reflujo— ni mejora la calidad de vida o las úlceras*, mientras añade molestias, sujeciones y complicaciones. La conducta correcta es la *alimentación oral confortable* adaptada, junto con tratamiento sintomático de las complicaciones. Y algo esencial: no es *eutanasia*, porque no se realiza ninguna acción dirigida a causar la muerte, sino que se deja que la enfermedad siga su curso; ni es *rechazo*, porque no lo decide la paciente; la decisión debe compartirse con la familia y quedar razonada en la historia clínica.',
  no:{0:'El rechazo de tratamiento lo ejerce el paciente, y esta paciente no puede expresar su voluntad.',1:'No hay eutanasia: no se realiza ninguna acción dirigida a causar la muerte.',3:'La obstinación terapéutica sería justamente lo contrario: colocar la sonda pese a su falta de beneficio demostrado.'},
  trampa:'Se percibe como abandono no poner la sonda. La evidencia demuestra que en la demencia avanzada la sonda no aporta beneficio y sí molestias.',
  dx:[],
  obj:'Fundamentar la limitación del esfuerzo terapéutico en la demencia avanzada con disfagia.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con recomendaciones de la American Geriatrics Society y de SECPAL.'
},
'MIR-2022-M194': {
  esp:'Salud Pública', tema:'Prevención', sub:'Niveles de prevención',
  clave:'Detectar precozmente un problema ya existente pero no manifestado es prevención SECUNDARIA.',
  exp:'Los cuatro niveles de prevención se ordenan según el momento de la historia natural en que se interviene. La *primaria* actúa *antes de que exista* el problema, para evitar que aparezca: vacunación, educación sanitaria, campañas contra la violencia de género. La *secundaria* actúa cuando el problema *ya existe pero aún no se ha manifestado* o no ha sido identificado, para detectarlo pronto y limitar el daño: es el terreno del *cribado* y de la *detección precoz*, y es exactamente lo que hace el médico en este caso al descubrir, a partir de una consulta por mareos y de una anamnesis cuidadosa, una situación de *violencia de pareja* que la paciente nunca había verbalizado. La *terciaria* actúa cuando el problema ya está establecido y busca reducir secuelas y rehabilitar: sería el acompañamiento, el apoyo psicológico y la rehabilitación posteriores. Y la *cuaternaria*, un concepto propio de la medicina de familia, consiste en proteger al paciente del *exceso de intervención médica* y del daño derivado de pruebas y tratamientos innecesarios. Vale la pena señalar que el papel del clínico aquí es precisamente el que la pregunta destaca: la *hiperfrecuentación* con síntomas inespecíficos es uno de los indicadores de sospecha de violencia.',
  no:{0:'La prevención primaria actuaría ANTES de que existiera la violencia, con educación y sensibilización.',2:'La terciaria correspondería a la rehabilitación y la reducción de secuelas una vez reconocido y abordado el problema.',3:'La cuaternaria protege al paciente del exceso de intervención médica, que no es lo que ocurre aquí.'},
  trampa:'Se etiqueta de prevención primaria por tratarse de una intervención social. El criterio es el momento: aquí el daño ya existe, solo que no estaba detectado.',
  dx:[],
  obj:'Clasificar una intervención en el nivel de prevención correspondiente.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Piédrola Gil, Medicina Preventiva y Salud Pública.'
},
'MIR-2022-M191': {
  esp:'Medicina Interna', tema:'Endocrinología', sub:'Síndrome metabólico',
  clave:'Cumple cuatro criterios ATP III: perímetro 104, triglicéridos 160, HDL 30 y tensión 136/89. La glucemia de 88 es normal.',
  exp:'Los criterios *ATP III* del síndrome metabólico son cinco y basta con *tres* para el diagnóstico; conviene contarlos uno a uno. El *perímetro abdominal* debe superar los *102 cm en el varón* y los 88 en la mujer: aquí es de *104*, luego *suma*. Los *triglicéridos* deben ser iguales o mayores de *150*: son *160*, *suma*. El *colesterol HDL* debe ser inferior a *40 en el varón* y a 50 en la mujer: es de *30*, *suma*. La *presión arterial* debe ser igual o superior a *130/85*, y basta con que se cumpla uno de los dos valores: *136/89* cumple ambos, *suma*. Y la *glucemia basal* debe ser igual o superior a *110 mg/dL* en la definición original: es de *88*, es decir, *normal*, y *no suma*. El total son por tanto *cuatro criterios*. El paciente tiene además dos factores de riesgo que no forman parte de la definición pero que agravan mucho su pronóstico —*tabaquismo* de 20 cigarrillos y *sedentarismo*—, y la intervención de mayor rendimiento es precisamente la modificación del estilo de vida.',
  no:{0:'Dos criterios se quedan cortos: cumple cuatro de los cinco.',1:'Tres tampoco: la única variable que no suma es la glucemia.',3:'Cinco exigiría también la glucemia alterada, y es de 88, plenamente normal.'},
  trampa:'Se cuenta la tensión de 136/89 como normal. El umbral del síndrome metabólico es 130/85, mucho más bajo que el de hipertensión.',
  dx:['Síndrome metabólico'],
  obj:'Aplicar los cinco criterios ATP III del síndrome metabólico.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con el Adult Treatment Panel III del NCEP.'
},
'MIR-2022-M210': {
  esp:'Medicina Interna', tema:'Cardiología', sub:'Prevención secundaria',
  clave:'Con LDL en 68 y HbA1c normal, lo que más eventos evita es DEJAR DE FUMAR, caminar y perder peso.',
  exp:'La pregunta obliga a comparar magnitudes de beneficio, y para eso hay que revisar cada cifra. El *LDL está en 68*, es decir, por debajo del objetivo clásico de 70 en prevención secundaria y con el paciente ya en atorvastatina de alta intensidad; hay margen para ser más exigente según guías recientes, pero el beneficio marginal es pequeño. La *glucemia de 115 con HbA1c de 5,7%* corresponde a una prediabetes que se aborda con dieta y ejercicio, no con fármacos. La *tensión de 140/85* está discretamente alta y merece optimizarse, pero de nuevo el beneficio añadido es modesto. Frente a todo eso, el *abandono del tabaco* es, con diferencia, la intervención más eficaz en un paciente que fuma tras un infarto: reduce el riesgo de reinfarto y la mortalidad en torno a un *tercio o la mitad* en los años siguientes, un efecto que ningún fármaco iguala, y el beneficio empieza en semanas. A ello se suman el *ejercicio regular* y la *pérdida de peso*, que además mejorarán de paso la tensión, la glucemia y el perfil lipídico. Es un buen recordatorio de que en prevención secundaria lo que más rinde no siempre se receta.',
  no:{0:'Optimizar la tensión es razonable pero su beneficio adicional es mucho menor que el de dejar de fumar.',1:'El LDL de 68 está en objetivo con estatina de alta intensidad: el margen de mejora es pequeño.',2:'Una HbA1c de 5,7% no requiere fármaco: se trata con dieta y ejercicio.'},
  trampa:'Se busca qué fármaco añadir o subir. La medida con mayor impacto en este paciente no está en la receta.',
  dx:[],
  obj:'Jerarquizar las intervenciones de prevención secundaria por su magnitud de beneficio.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías ESC de prevención cardiovascular.'
},
'MIR-2022-M190': {
  esp:'Medicina Interna', tema:'Cardiología', sub:'Betabloqueantes en insuficiencia cardiaca',
  clave:'Fracción de eyección del 30% y solo lleva IECA: falta el BETABLOQUEANTE, uno de los pilares que reducen mortalidad.',
  exp:'El paciente tiene una *insuficiencia cardiaca con fracción de eyección reducida* del 30% y está *estable y asintomático* tras el ingreso, que es el momento idóneo para completar el tratamiento de fondo. Lleva *enalapril*, es decir, el primer pilar, pero le falta el segundo: un *betabloqueante* con beneficio demostrado en esta indicación, y solo tres lo tienen —*bisoprolol*, *carvedilol* y *metoprolol succinato*, además del nebivolol en el anciano—. Su beneficio en *mortalidad* está sólidamente demostrado, se inicia a *dosis bajas* en paciente estable y euvolémico, y se titula al alza cada dos semanas hasta la dosis diana; una frecuencia de 78 lpm deja margen sobrado. Las alternativas son incorrectas por motivos concretos: el *diltiazem*, como el verapamilo, es un calcioantagonista *no dihidropiridínico con efecto inotrópico negativo* y está *contraindicado* en la fracción de eyección reducida; cambiar el enalapril por losartán no aporta nada, ya que los ARA-II se reservan para quienes no toleran el IECA por tos; y no hacer nada desaprovecha una intervención que salva vidas.',
  no:{1:'El diltiazem es inotrópico negativo y está contraindicado en la insuficiencia cardiaca con fracción de eyección reducida.',2:'El losartán se reserva para la intolerancia al IECA, típicamente por tos: el cambio no aporta beneficio.',3:'No hacer nada deja al paciente sin uno de los pilares con beneficio demostrado en mortalidad.'},
  trampa:'Se piensa que estando asintomático no hay que tocar nada. El tratamiento de la insuficiencia cardiaca es pronóstico, no solo sintomático.',
  dx:[],
  obj:'Completar el tratamiento pronóstico de la insuficiencia cardiaca con fracción de eyección reducida.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías ESC de insuficiencia cardiaca.'
},
'MIR-2022-M197': {
  esp:'Medicina Interna', tema:'Gastroenterología', sub:'Anemia ferropénica en el varón',
  clave:'Anemia MICROCÍTICA en un varón de 59 años: hay que descartar cáncer colorrectal. Tacto rectal y colonoscopia.',
  exp:'La analítica describe una *anemia ferropénica*: *VCM de 75*, es decir, microcítica, con un *ancho de distribución eritrocitaria del 22%*, muy elevado, que refleja la anisocitosis típica de la falta de hierro. Y aquí lo determinante es el *contexto epidemiológico*: en un *varón* o en una *mujer posmenopáusica*, una ferropenia significa *pérdida crónica de sangre por el tubo digestivo* mientras no se demuestre lo contrario, porque no existen las pérdidas menstruales que la explican en la mujer fértil. La causa que hay que descartar con prioridad absoluta es el *cáncer colorrectal*, sobre todo el de colon derecho, que sangra de forma lenta e invisible y se manifiesta precisamente así, con anemia y astenia, sin alterar el ritmo intestinal. Por eso el paso inicial correcto es el *tacto rectal* —que puede palpar un tumor bajo y valorar el aspecto de las heces— y la *colonoscopia*, que suele completarse con gastroscopia en el mismo procedimiento. Y un detalle importante: el *test de sangre oculta en heces no debe usarse* en este escenario, porque un resultado negativo no descarta nada y solo retrasaría el estudio.',
  no:{1:'La disnea es consecuencia de la anemia: no hay datos de enfermedad respiratoria que justifiquen espirometría ni broncoscopia.',2:'La haptoglobina y el Coombs se piden ante hemólisis, que cursa con VCM normal o alto y reticulocitosis, no con microcitosis.',3:'El déficit de B12 daría anemia MACROCÍTICA, exactamente lo contrario de lo que se ve aquí.'},
  trampa:'Se trata la anemia con hierro y se cita para control. En un varón, la ferropenia es un síntoma que obliga a buscar el tumor que sangra.',
  dx:['Cáncer colorrectal','Angiodisplasia','Enfermedad celíaca','Úlcera péptica'],
  obj:'Investigar el tubo digestivo ante una anemia ferropénica en el varón.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías BSG sobre anemia ferropénica.'
},
'MIR-2022-M198': {
  esp:'Emergencias', tema:'Toxicología', sub:'Intoxicación por paracetamol',
  clave:'Niveles en rango tóxico: se inicia N-ACETILCISTEÍNA sin esperar, y se mantiene según evolución analítica, no por un tiempo fijo.',
  exp:'La intoxicación por paracetamol tiene una trampa clínica que aquí está bien representada: la paciente está *nauseosa, pálida y sudorosa* pero con *función hepática y coagulación normales*, porque en las primeras 24 horas los síntomas son inespecíficos y la citólisis todavía no ha aparecido; el daño hepático máximo se produce entre las *72 y las 96 horas*. Por eso la decisión no se toma con las transaminasas sino con el *nomograma de Rumack-Matthew*, y si los niveles caen en rango de *probable toxicidad*, como aquí, hay que *iniciar N-acetilcisteína de inmediato*. Su mecanismo es reponer el *glutatión* que el metabolito tóxico NAPQI agota, y su eficacia es máxima en las primeras 8 a 10 horas, aunque sigue siendo beneficiosa más tarde, incluso con hepatotoxicidad establecida. Y el punto que la pregunta afina: *no se administra durante un tiempo fijo*; las pautas actuales prolongan el tratamiento *mientras persistan niveles detectables, transaminasas en ascenso o coagulopatía*, guiándose por la evolución analítica. Hay que vigilar además los criterios del King College por si procede el trasplante.',
  no:{0:'Observar sin tratar con niveles en rango tóxico desaprovecha la ventana de máxima eficacia del antídoto.',1:'La duración no es fija: se prolonga según niveles, transaminasas y coagulación.',2:'Repetir analíticas sin iniciar el antídoto es un error: el daño hepático se instaura después, y entonces ya es tarde.'},
  trampa:'Las pruebas hepáticas normales tranquilizan. A las 12 horas es lo esperable: la decisión se toma con los niveles, no con las transaminasas.',
  dx:['Intoxicación por paracetamol','Hepatitis vírica aguda','Intoxicación por otros fármacos'],
  obj:'Indicar N-acetilcisteína guiada por el nomograma y ajustar su duración a la evolución.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Goldfrank, Toxicologic Emergencies.'
},
'MIR-2022-M56': {
  esp:'Farmacología', tema:'Farmacocinética', sub:'Diuresis alcalina',
  clave:'El metotrexato es un ÁCIDO DÉBIL: alcalinizar la orina con bicarbonato lo ioniza y acelera su eliminación.',
  exp:'La eliminación renal de un fármaco depende de su *grado de ionización* en el túbulo, porque solo la fracción *no ionizada* —liposoluble— puede reabsorberse de vuelta a la sangre, mientras que la *ionizada* queda *atrapada* en la orina y se elimina. De ahí la regla general: los *ácidos débiles* se ionizan en medio *alcalino* y por tanto se eliminan mejor *alcalinizando* la orina; los *bases débiles* hacen lo contrario y se eliminan mejor acidificándola. El *metotrexato* es un ácido débil con *pKa entre 4 y 5,5*, de modo que con un pH urinario *menor de 7*, como el del paciente, permanece poco ionizado, se reabsorbe y además *precipita* en los túbulos formando cristales, lo que agrava la nefrotoxicidad y perpetúa el retraso en su eliminación. La actuación correcta es la *alcalinización urinaria con bicarbonato sódico intravenoso*, buscando un pH por encima de 7, junto con hidratación abundante; a ello se añade el *rescate con ácido folínico*. El *cloruro amónico* haría lo contrario, acidificar, empeorando la situación.',
  no:{0:'El cloruro amónico ACIDIFICA la orina, lo que reduciría la ionización del metotrexato y agravaría su acumulación y precipitación.',2:'La vía enteral no sirve: el metotrexato se ha administrado por vía intravenosa, no hay absorción digestiva que reducir.',3:'La furosemida con pH neutro no corrige el problema de fondo, que es el grado de ionización del fármaco en el túbulo.'},
  trampa:'Se piensa en forzar la diuresis con un diurético. Lo que importa aquí no es el volumen de orina sino su pH.',
  dx:[],
  obj:'Aplicar el principio de atrapamiento iónico para acelerar la eliminación renal de un ácido débil.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con Goodman y Gilman, Bases Farmacológicas de la Terapéutica.'
},
'MIR-2022-M208': {
  esp:'Medicina Interna', tema:'Neumología', sub:'Distrés respiratorio por SARS-CoV-2',
  clave:'PCR positiva con infiltrados bilaterales y PaO2/FiO2 de 250: neumonía por SARS-CoV-2 con distrés respiratorio agudo.',
  exp:'El diagnóstico se construye aplicando directamente los *criterios de Berlín*. La *causa* está identificada por la *PCR positiva* para SARS-CoV-2 y por un cuadro de cuatro días con fiebre, tos y crepitantes bibasales. La *radiología* muestra *infiltrados bilaterales* con patrón alveolo-intersticial *periférico*, muy característico de la neumonía por este virus, y no explicables por derrame ni por atelectasia. Y la *oxigenación* da un cociente *PaO2/FiO2 de 250*, es decir, igual o inferior a 300, lo que cumple el criterio de distrés y lo clasifica además como *leve*, ya que el rango leve va de 200 a 300, el moderado de 100 a 200 y el grave por debajo de 100. La *hipoventilación alveolar* queda descartada porque en el distrés lo característico es el *shunt* con hipoxemia refractaria y, si acaso, hipocapnia por taquipnea. La *hemorragia pulmonar* exigiría hemoptisis y caída del hematocrito, y una *neumonía bacteriana* sobreañadida requeriría datos que aquí no constan. El manejo se apoya en oxigenoterapia escalonada, dexametasona y ventilación protectora si progresa.',
  no:{0:'La hemorragia pulmonar cursaría con hemoptisis y descenso del hematocrito, no descritos.',1:'Nada indica sobreinfección bacteriana: la PCR positiva y el patrón radiológico explican el cuadro.',3:'En el distrés el mecanismo es el shunt con hipoxemia refractaria, no la hipoventilación alveolar.'},
  trampa:'Se pasa por alto que un cociente de 250 ya define distrés. El umbral es 300, no la necesidad de intubación.',
  dx:['Distrés respiratorio agudo por SARS-CoV-2','Neumonía bacteriana','Edema pulmonar cardiogénico'],
  obj:'Aplicar los criterios de Berlín para diagnosticar y graduar el distrés respiratorio.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con la definición de Berlín y guías de la OMS sobre COVID-19.'
},
'MIR-2022-M209': {
  esp:'Medicina Interna', tema:'Neumología', sub:'Neumonitis por hipersensibilidad',
  clave:'Patrón RESTRICTIVO con crepitantes finos e infiltrados subpleurales tras usar un HUMIDIFICADOR: neumonitis por hipersensibilidad.',
  exp:'Lo primero que hay que ver es que la espirometría *no es obstructiva*: el cociente *FEV1/FVC es de 0,92*, es decir, alto, con *FVC reducida al 68%*, lo que configura un patrón *restrictivo* y descarta de plano el asma. A eso se suman *crepitantes finos en bases* y una TC con *infiltrados subpleurales y patrón reticular* en lóbulos inferiores, con áreas parcheadas en superiores: enfermedad *intersticial*. Y hay un desencadenante temporal claro: un *humidificador* usado cada noche desde hace *tres meses*, dispositivo clásicamente implicado en la neumonitis por hipersensibilidad por la aerosolización de *actinomicetos termófilos, hongos y bacterias* que colonizan su depósito —el llamado pulmón del humidificador—. La enfermedad se debe a una respuesta inmune a esos antígenos inhalados, y el tratamiento fundamental es la *retirada del agente*, que en las formas subagudas suele ser suficiente, añadiendo corticoides si la afectación es importante. El reflujo y la alergia al perro son distractores razonables pero no explican ni la restricción ni el patrón intersticial de la TC.',
  no:{1:'El reflujo puede producir tos crónica, pero no explica la restricción espirométrica ni los infiltrados intersticiales.',2:'No hay crisis asmática: el patrón espirométrico es restrictivo, no obstructivo.',3:'La alergia al perro produciría rinoconjuntivitis y asma, con patrón obstructivo, y convive con él desde hace cinco años sin problemas.'},
  trampa:'Se trata como un asma mal controlada porque hay disnea y sibilancias. La espirometría desmiente la obstrucción, y la clave está en el humidificador.',
  dx:['Neumonitis por hipersensibilidad','Asma','Fibrosis pulmonar idiopática','Reflujo gastroesofágico'],
  obj:'Reconocer la neumonitis por hipersensibilidad y la importancia de retirar el antígeno.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con guías ATS/JRS/ALAT sobre neumonitis por hipersensibilidad.'
},
'MIR-2022-M49': {
  esp:'Medicina Interna', tema:'Neumología', sub:'Deshabituación tabáquica',
  clave:'El cigarrillo electrónico NO está en los protocolos de primera línea: faltan datos de eficacia y seguridad a largo plazo.',
  exp:'La *cesación tabáquica* es la única intervención que modifica realmente la historia natural de la EPOC, frenando la caída acelerada del FEV1, y por eso conviene conocer bien su arsenal. Los tratamientos de *primera línea* con eficacia y seguridad demostradas son tres: la *terapia sustitutiva con nicotina* en cualquiera de sus formas —parches, chicles, comprimidos, espray—, el *bupropión*, un antidepresivo que inhibe la recaptación de dopamina y noradrenalina, y la *vareniclina*, agonista parcial de los receptores nicotínicos alfa-4-beta-2, que es la de mayor eficacia. Todos ellos deben acompañarse de *apoyo conductual*, que multiplica sus resultados. El *cigarrillo electrónico*, en cambio, *no figura* en los protocolos de primera elección: aunque algunos ensayos sugieren cierta eficacia, persisten dudas sobre su *seguridad a largo plazo*, sobre la composición de los aerosoles, sobre el riesgo de mantener la dependencia a la nicotina y sobre su papel como puerta de entrada al tabaquismo en jóvenes, además de los casos descritos de lesión pulmonar aguda asociada a vapeo.',
  no:{0:'El parche de nicotina es tratamiento de primera línea con eficacia y seguridad bien establecidas.',1:'El bupropión es de primera línea, con la precaución de no usarlo en pacientes con antecedente de convulsiones.',2:'La vareniclina es de primera línea y la de mayor eficacia demostrada.'},
  trampa:'Se asume que si ayuda a dejar de fumar ya está recomendado. Los protocolos exigen evidencia de eficacia Y de seguridad, y esa segunda parte falta.',
  dx:[],
  obj:'Conocer los tratamientos de primera línea de la deshabituación tabáquica.',
  ref:'Examen MIR 2022, Ministerio de Sanidad de España. Contrastado con la guía GOLD y recomendaciones de SEPAR.'
}

});
