/* ============================================================
   MAZO CURADO DE FLASHCARDS
   Para los días en que no hay tiempo de sentarse a hacer preguntas.

   Criterio de qué entra aquí: lo que se olvida y se pregunta.
   Cifras, umbrales, criterios, secuencias y pares que se
   confunden entre sí. NO conceptos largos: eso son las preguntas.

   Anverso corto y concreto. Reverso que se lee en 5 segundos.
   El campo `mas` es el matiz que se lee solo si te interesa.
   ============================================================ */
window.TARJETAS = [

/* ===================== CARDIOLOGÍA ===================== */
{id:'T-001', esp:'Medicina Interna', tema:'Cardiología', a:'¿En cuántos minutos debe hacerse el ECG ante sospecha de síndrome coronario agudo?', b:'En los primeros 10 minutos del primer contacto médico.', mas:'Es lo único que separa de inmediato un SCACEST de un SCASEST.'},
{id:'T-002', esp:'Medicina Interna', tema:'Cardiología', a:'Infarto inferior + hipotensión + yugulares ingurgitadas + pulmones limpios. ¿Qué es y qué NO se puede dar?', b:'Infarto de ventrículo derecho. Prohibidos nitratos y diuréticos: depende de la precarga. Se carga volumen.', mas:'Se confirma con derivaciones derechas (V4R).'},
{id:'T-003', esp:'Medicina Interna', tema:'Cardiología', a:'Los cuatro pilares de la insuficiencia cardíaca con FEVI reducida', b:'IECA/ARA-II o ARNI · betabloqueante · antagonista mineralocorticoide · inhibidor de SGLT2.', mas:'Los cuatro reducen mortalidad. Diurético y digoxina alivian, no salvan.'},
{id:'T-004', esp:'Medicina Interna', tema:'Cardiología', a:'CHA₂DS₂-VASc: ¿qué puntúa 2 en vez de 1?', b:'Edad ≥75 años y el antecedente de ictus o AIT. El resto puntúa 1.', mas:'Anticoagular con ≥2 en hombres y ≥3 en mujeres.'},
{id:'T-005', esp:'Medicina Interna', tema:'Cardiología', a:'Soplo nuevo postinfarto CON frémito. ¿Qué complicación es?', b:'Comunicación interventricular. La rotura de pared libre NO da soplo ni frémito: da taponamiento.', mas:'La CIV muestra salto oximétrico en ventrículo derecho.'},
{id:'T-006', esp:'Medicina Interna', tema:'Cardiología', a:'¿Cuándo aparecen las complicaciones mecánicas del infarto?', b:'Entre el segundo y el séptimo día, cuando se reblandece el tejido necrótico.', mas:'No en el primer día.'},
{id:'T-007', esp:'Medicina Interna', tema:'Cardiología', a:'Tercer ruido y cuarto ruido: ¿qué significa cada uno?', b:'R3: llenado rápido, sobrecarga de VOLUMEN. R4: contracción auricular contra ventrículo RÍGIDO.', mas:'Ninguno de los dos indica problema valvular.'},
{id:'T-008', esp:'Medicina Interna', tema:'Cardiología', a:'Estenosis aórtica severa: ¿qué marca el cambio de pronóstico?', b:'La aparición de síntomas: angina, síncope o disnea. Ahí se indica reemplazo valvular.', mas:'La edad no contraindica: existe la vía percutánea.'},
{id:'T-009', esp:'Medicina Interna', tema:'Cardiología', a:'Joven con síncope, ondas Q profundas y soplo en borde esternal izquierdo bajo', b:'Miocardiopatía hipertrófica obstructiva. Las Q son de hipertrofia septal, no de infarto.', mas:'Su soplo AUMENTA con Valsalva; el de la estenosis aórtica disminuye.'},
{id:'T-010', esp:'Medicina Interna', tema:'Cardiología', a:'Pericarditis aguda: patrón del ECG y tratamiento', b:'Elevación del ST difusa y CÓNCAVA con descenso del PR. Tratamiento: AINE + colchicina 3 meses.', mas:'La colchicina reduce a la mitad las recurrencias.'},
{id:'T-011', esp:'Medicina Interna', tema:'Cardiología', a:'Bloqueo AV de 2.º grado Mobitz II con síncope. ¿Qué hace falta antes de poner marcapasos?', b:'Nada más. La indicación es directa: no hacen falta Holter ni otros estudios.', mas:'Alto riesgo de progresar a bloqueo completo.'},

/* ===================== NEUMOLOGÍA ===================== */
{id:'T-020', esp:'Medicina Interna', tema:'Neumología', a:'Exacerbación de EPOC con pH 7,28. ¿Qué intervención cambia el pronóstico?', b:'Ventilación mecánica NO invasiva. Reduce intubación y mortalidad.', mas:'Objetivo de saturación 88-92%, no 100%.'},
{id:'T-021', esp:'Medicina Interna', tema:'Neumología', a:'Los cinco ítems del CURB-65', b:'Confusión · Urea >44 mg/dL · FR ≥30 · PA sistólica <90 o diastólica ≤60 · Edad ≥65.', mas:'0-1 ambulatorio · 2 ingreso · ≥3 valorar UCI.'},
{id:'T-022', esp:'Medicina Interna', tema:'Neumología', a:'¿Cuándo NO sirve el dímero D?', b:'Cuando la probabilidad clínica es ALTA. Solo vale para descartar en probabilidad baja o intermedia.', mas:'Con Wells alto se va directo a angiotomografía.'},
{id:'T-023', esp:'Medicina Interna', tema:'Neumología', a:'Criterios de Light: ¿cuántos hacen falta para llamarlo exudado?', b:'UNO solo. Proteínas pl/sérica >0,5 · LDH pl/sérica >0,6 · LDH pleural >2/3 del límite superior normal.', mas:'El error clásico es exigir que se cumplan todos.'},
{id:'T-024', esp:'Medicina Interna', tema:'Neumología', a:'Exudado pleural LINFOCITARIO con citología negativa. ¿Qué se pide?', b:'Adenosina desaminasa (ADA): alto rendimiento para tuberculosis pleural.', mas:'La baciloscopia del líquido es poco sensible.'},
{id:'T-025', esp:'Medicina Interna', tema:'Neumología', a:'Asma con clínica típica pero espirometría normal. ¿Siguiente paso?', b:'Prueba de provocación con metacolina. Su valor está en el resultado NEGATIVO: descarta asma.', mas:'Una espirometría normal entre crisis es lo esperable.'},
{id:'T-026', esp:'Medicina Interna', tema:'Neumología', a:'Crisis asmática con tórax SILENTE. ¿Qué significa?', b:'Gravedad extrema: no entra aire suficiente para generar sibilancias. NO es mejoría.', mas:'Se acompaña de espiración alargada y percusión timpánica.'},
{id:'T-027', esp:'Medicina Interna', tema:'Neumología', a:'¿Qué parámetro separa enfisema de bronquitis crónica?', b:'La DLCO: BAJA en el enfisema, conservada en la bronquitis crónica.', mas:'Ambos comparten FEV1/FVC <0,70.'},
{id:'T-028', esp:'Medicina Interna', tema:'Neumología', a:'Derrame pleural: ¿hacia dónde se desvía la tráquea? ¿Y en la atelectasia?', b:'El derrame EMPUJA al lado contrario. La atelectasia TIRA hacia el mismo lado.', mas:'Ambos dan matidez; la dirección los separa.'},
{id:'T-029', esp:'Medicina Interna', tema:'Neumología', a:'Neumotórax a tensión: ¿qué prueba se pide antes de descomprimir?', b:'Ninguna. El diagnóstico es clínico y pedir radiografía es el error.', mas:'Hipotensión + desviación traqueal + ausencia de murmullo.'},

/* ===================== ENDOCRINOLOGÍA ===================== */
{id:'T-040', esp:'Medicina Interna', tema:'Endocrinología', a:'Criterios diagnósticos de diabetes: los cuatro números', b:'Glucemia ayunas ≥126 · a las 2 h en SOG ≥200 · HbA1c ≥6,5% · al azar ≥200 con síntomas.', mas:'Prediabetes: ayunas 100-125, HbA1c 5,7-6,4, 2 h 140-199.'},
{id:'T-041', esp:'Medicina Interna', tema:'Endocrinología', a:'Cetoacidosis diabética con potasio de 3,0. ¿Qué se hace ANTES de la insulina?', b:'Reponer potasio. Con K <3,3 la insulina puede provocar hipopotasemia letal.', mas:'Orden: líquidos → potasio → insulina.'},
{id:'T-042', esp:'Medicina Interna', tema:'Endocrinología', a:'Umbral de filtrado glomerular que contraindica la metformina', b:'Por debajo de 30 mL/min se suspende. Entre 30 y 45 se reduce la dosis y no se inicia.', mas:'También se suspende antes de contraste yodado.'},
{id:'T-043', esp:'Medicina Interna', tema:'Endocrinología', a:'Tirotoxicosis con gammagrafía sin captación. ¿Qué distingue la facticia de la tiroiditis?', b:'La TIROGLOBULINA: baja en la facticia (hormona exógena), alta en la tiroiditis (destrucción glandular).', mas:'La gammagrafía es igual en las dos.'},
{id:'T-044', esp:'Medicina Interna', tema:'Endocrinología', a:'Hormigueos en las manos la noche de una tiroidectomía total', b:'Hipocalcemia por hipoparatiroidismo posquirúrgico. Calcio y vitamina D, no sedantes.', mas:'Progresa a tetania, laringoespasmo y convulsiones.'},
{id:'T-045', esp:'Medicina Interna', tema:'Endocrinología', a:'Corticoide 8 meses ya controlado. ¿Se puede suspender de golpe?', b:'No: hay supresión del eje. Retirada progresiva en semanas o meses o hay crisis suprarrenal.', mas:'La atrofia suprarrenal tarda en recuperarse.'},
{id:'T-046', esp:'Medicina Interna', tema:'Endocrinología', a:'Hiperparatiroidismo primario ASINTOMÁTICO: ¿cuándo se opera?', b:'Litiasis renal, osteoporosis o fractura, filtrado bajo, calcio >1 mg/dL sobre el límite, o edad <50 años.', mas:'La litiasis ya es lesión de órgano diana: es quirúrgico.'},
{id:'T-047', esp:'Medicina Interna', tema:'Endocrinología', a:'GnRH pulsátil frente a GnRH continua: ¿qué hace cada una?', b:'Pulsátil ESTIMULA el eje (bomba de infusión, fertilidad). Continua lo FRENA (análogos como triptorelina).', mas:'Misma molécula, efecto opuesto según la pauta.'},
{id:'T-048', esp:'Medicina Interna', tema:'Endocrinología', a:'Macroadenoma hipofisario con prolactina de 480 µg/L. ¿Cirugía?', b:'No: prolactinoma. Es el único tumor hipofisario con tratamiento MÉDICO de primera línea (cabergolina).', mas:'Compresión por tallo rara vez pasa de 150 µg/L.'},

/* ===================== NEFROLOGÍA ===================== */
{id:'T-060', esp:'Medicina Interna', tema:'Nefrología', a:'Prerrenal frente a necrosis tubular aguda: los dos números', b:'Prerrenal: FeNa <1%, sedimento limpio. NTA: FeNa >2%, cilindros granulosos pardos.', mas:'El túbulo dañado no puede retener sodio.'},
{id:'T-061', esp:'Medicina Interna', tema:'Nefrología', a:'Hiperpotasemia con cambios en el ECG. ¿Qué se pone PRIMERO?', b:'Gluconato de calcio. No baja el potasio, pero estabiliza la membrana en minutos.', mas:'Después insulina con glucosa, y luego diálisis.'},
{id:'T-062', esp:'Medicina Interna', tema:'Nefrología', a:'Síndrome nefrótico con espículas y anti-PLA2R positivo', b:'Nefropatía membranosa. El anti-PLA2R es casi específico de la forma primaria.', mas:'Causa más frecuente de nefrótico en adulto no diabético.'},
{id:'T-063', esp:'Medicina Interna', tema:'Nefrología', a:'Fracaso renal con eosinófilos en orina tras un antibiótico', b:'Nefritis intersticial aguda por hipersensibilidad. Complemento NORMAL.', mas:'Se retira el fármaco y suele revertir.'},
{id:'T-064', esp:'Medicina Interna', tema:'Nefrología', a:'¿Por qué la creatinina detecta tarde la pérdida de función renal?', b:'La relación es hiperbólica: puede perderse la mitad del filtrado antes de que salga del rango normal.', mas:'En el anciano con poca masa muscular engaña aún más.'},
{id:'T-065', esp:'Medicina Interna', tema:'Nefrología', a:'Hematuria macroscópica: ¿nefropatía IgA o postinfecciosa?', b:'IgA: A LA VEZ que la infección y recurrente. Postinfecciosa: 1-3 semanas DESPUÉS, episodio único y C3 bajo.', mas:'El intervalo es lo que decide.'},

/* ===================== DIGESTIVO ===================== */
{id:'T-080', esp:'Medicina Interna', tema:'Gastroenterología', a:'Cirrótico que sangra: ¿qué medida reduce la mortalidad además de la endoscopia?', b:'Antibiótico profiláctico, habitualmente ceftriaxona.', mas:'El ácido tranexámico NO sirve (ensayo HALT-IT).'},
{id:'T-081', esp:'Medicina Interna', tema:'Gastroenterología', a:'Umbral de polimorfonucleares en líquido ascítico para diagnosticar PBE', b:'≥250 PMN/mm³. Se trata sin esperar al cultivo, que sale negativo a menudo.', mas:'Añadir albúmina previene el síndrome hepatorrenal.'},
{id:'T-082', esp:'Medicina Interna', tema:'Gastroenterología', a:'Pancreatitis aguda: ¿qué NO se hace?', b:'Ni tomografía inicial, ni antibiótico profiláctico, ni nutrición parenteral de entrada.', mas:'Sí: hidratación enérgica precoz y nutrición ENTERAL.'},
{id:'T-083', esp:'Medicina Interna', tema:'Gastroenterología', a:'Úlcera con "vaso visible" no sangrante. ¿Se trata endoscópicamente?', b:'Sí: Forrest IIa, riesgo de resangrado ~50%. Terapéutica endoscópica + IBP intravenoso en dosis altas.', mas:'La combinación reduce resangrado y mortalidad.'},
{id:'T-084', esp:'Medicina Interna', tema:'Gastroenterología', a:'¿Qué úlcera obliga SIEMPRE a rebiopsiar tras el tratamiento?', b:'La GÁSTRICA. Un adenocarcinoma ulcerado puede tener bordes benignos y primera biopsia negativa.', mas:'Endoscopia de control a las 8-12 semanas.'},
{id:'T-085', esp:'Medicina Interna', tema:'Gastroenterología', a:'Diarrea acuosa crónica con endoscopia NORMAL', b:'Colitis microscópica. Hay que biopsiar aunque la mucosa parezca sana.', mas:'Colágena: banda de colágeno subepitelial con tricrómico.'},
{id:'T-086', esp:'Medicina Interna', tema:'Gastroenterología', a:'Impactación alimentaria recurrente en joven con asma y alergias', b:'Esofagitis eosinofílica. Biopsias esofágicas escalonadas para contar eosinófilos.', mas:'No confundir con reflujo: la atopia es la pista.'},
{id:'T-087', esp:'Medicina Interna', tema:'Gastroenterología', a:'Hepatocarcinoma con invasión de rama portal. ¿Qué estadio?', b:'BCLC C, avanzado. Ni cirugía, ni trasplante, ni quimioembolización: tratamiento sistémico.', mas:'La invasión vascular pesa más que el tamaño.'},

/* ===================== INFECTOLOGÍA ===================== */
{id:'T-100', esp:'Medicina Interna', tema:'Infectología', a:'Dengue: ¿qué significa que baje la fiebre al 4.º-5.º día?', b:'Que empieza la FASE CRÍTICA de fuga capilar. No es mejoría.', mas:'Dolor abdominal, vómitos y hemoconcentración = signos de alarma.'},
{id:'T-101', esp:'Medicina Interna', tema:'Infectología', a:'Signos de alarma del dengue', b:'Dolor abdominal intenso · vómitos persistentes · acumulación de líquidos · sangrado de mucosas · letargia o irritabilidad · hepatomegalia >2 cm · hematocrito que sube con plaquetas que bajan.', mas:'Cualquiera obliga a hospitalizar e hidratar por vía intravenosa.'},
{id:'T-102', esp:'Medicina Interna', tema:'Infectología', a:'Meningitis bacteriana: ¿cuándo se da la dexametasona?', b:'ANTES o junto con la primera dosis de antibiótico. Nunca después.', mas:'El antibiótico jamás espera a la tomografía.'},
{id:'T-103', esp:'Medicina Interna', tema:'Infectología', a:'¿Cuándo SÍ hace falta TAC antes de la punción lumbar?', b:'Focalidad neurológica · papiledema · convulsiones · inmunosupresión · alteración grave de la conciencia.', mas:'Fuera de eso solo añade retraso.'},
{id:'T-104', esp:'Medicina Interna', tema:'Infectología', a:'CD4 <200: ¿qué profilaxis?', b:'Trimetoprim-sulfametoxazol frente a Pneumocystis jirovecii.', mas:'CD4 <50: profilaxis frente a complejo Mycobacterium avium.'},
{id:'T-105', esp:'Medicina Interna', tema:'Infectología', a:'Sufusión conjuntival + mialgias en pantorrillas + ictericia + falla renal, tras lluvias', b:'Leptospirosis. Síndrome de Weil en la forma grave.', mas:'En zona endémica no todo síndrome febril es dengue.'},
{id:'T-106', esp:'Medicina Interna', tema:'Infectología', a:'Serología de hepatitis B: ¿qué marcador fecha la infección?', b:'El anti-HBc: IgM = aguda, IgG = antigua. El HBsAg solo dice que está activa.', mas:'Vacunado: anti-HBs aislado, sin anti-HBc.'},
{id:'T-107', esp:'Medicina Interna', tema:'Infectología', a:'Criterios de malaria GRAVE (los principales)', b:'Parasitemia >5% · alteración de conciencia · fracaso renal · acidosis · hipoglucemia · anemia grave.', mas:'Tratamiento: ARTESUNATO INTRAVENOSO. Nada oral.'},
{id:'T-108', esp:'Medicina Interna', tema:'Infectología', a:'Parásito intraeritrocitario transmitido por GARRAPATA que imita malaria', b:'Babesia. Tétrada en cruz de Malta, sin pigmento.', mas:'Mismo vector Ixodes que la enfermedad de Lyme.'},
{id:'T-109', esp:'Medicina Interna', tema:'Infectología', a:'Sepsis por E. coli productora de BLEE. ¿Qué antibiótico?', b:'Carbapenémico (ertapenem en la urinaria).', mas:'BLEE inactiva penicilinas, todas las cefalosporinas y aztreonam.'},
{id:'T-110', esp:'Medicina Interna', tema:'Infectología', a:'Profilaxis postexposición a hepatitis B en NO vacunado', b:'Las dos cosas: inmunoglobulina específica + primera dosis de vacuna, en sitios distintos.', mas:'Preferiblemente en 24 h, siempre antes de 7 días.'},
{id:'T-111', esp:'Medicina Interna', tema:'Infectología', a:'Otitis externa maligna en diabético: ¿qué germen?', b:'Pseudomonas aeruginosa. No es la microbiología de la otitis media.', mas:'Es osteomielitis de base de cráneo: antibiótico prolongado IV.'},
{id:'T-112', esp:'Medicina Interna', tema:'Infectología', a:'Dolor desproporcionado con piel casi normal y sepsis rápida', b:'Fascitis necrotizante. Desbridamiento quirúrgico urgente.', mas:'La piel normal NO tranquiliza: la infección corre por la fascia.'},
{id:'T-113', esp:'Medicina Interna', tema:'Infectología', a:'Trasplante: ¿qué combinación serológica tiene más riesgo de CMV?', b:'Donante POSITIVO con receptor NEGATIVO. El virus entra con el órgano y el receptor no tiene defensas.', mas:'Obliga a profilaxis prolongada con valganciclovir.'},

/* ===================== NEUROLOGÍA ===================== */
{id:'T-130', esp:'Medicina Interna', tema:'Neurología', a:'Ventana de trombólisis en el ictus isquémico y paso previo obligado', b:'4,5 horas. Antes, SIEMPRE tomografía simple para descartar hemorragia.', mas:'La edad avanzada no es contraindicación por sí sola.'},
{id:'T-131', esp:'Medicina Interna', tema:'Neurología', a:'Cefalea en trueno con TAC normal a las 8 horas. ¿Se descarta hemorragia subaracnoidea?', b:'No. Punción lumbar buscando xantocromía. La sensibilidad de la TAC cae con las horas.', mas:'Repetir la TAC más tarde es aún menos sensible.'},
{id:'T-132', esp:'Medicina Interna', tema:'Neurología', a:'Parálisis facial: ¿qué dato separa central de periférica?', b:'La FRENTE. Si está afectada, es periférica. La frente tiene inervación cortical bilateral.', mas:'Bell periférica: corticoides orales en las primeras 72 h.'},
{id:'T-133', esp:'Medicina Interna', tema:'Neurología', a:'Ptosis con MIOSIS frente a ptosis con MIDRIASIS', b:'Miosis = síndrome de Horner (vía simpática). Midriasis = lesión del III par.', mas:'Horner doloroso tras esfuerzo: disección arterial.'},
{id:'T-134', esp:'Medicina Interna', tema:'Neurología', a:'Estado epiléptico: ¿a partir de cuántos minutos y con qué se trata?', b:'Más de 5 minutos de crisis continua. Primera línea: BENZODIACEPINA.', mas:'Segunda línea: fenitoína, valproato o levetiracetam.'},
{id:'T-135', esp:'Medicina Interna', tema:'Neurología', a:'Síncope frente a crisis epiléptica', b:'Síncope: pródromo, palidez, recuperación en <1 min, orientado enseguida. Convulsionar y orinarse NO lo descarta.', mas:'La crisis deja periodo postcrítico con desorientación.'},
{id:'T-136', esp:'Medicina Interna', tema:'Neurología', a:'Demencia rápida + mioclonías que persisten en el SUEÑO', b:'Creutzfeldt-Jakob. Proteína 14-3-3 en LCR y complejos periódicos en el EEG.', mas:'La 14-3-3 no es específica: apoya, no prueba.'},
{id:'T-137', esp:'Medicina Interna', tema:'Neurología', a:'¿Qué signo apunta a cuerpos de Lewy y NO a Alzheimer?', b:'Trastorno de conducta del sueño REM. También alucinaciones visuales precoces, fluctuación y parkinsonismo.', mas:'Es un marcador prodrómico de sinucleinopatía.'},
{id:'T-138', esp:'Medicina Interna', tema:'Neurología', a:'Cefalea que empeora al INCORPORARSE tras una punción lumbar', b:'Cefalea pospunción: es ortostática y cede al tumbarse.', mas:'Rebelde: parche hemático epidural.'},

/* ===================== REUMATOLOGÍA ===================== */
{id:'T-150', esp:'Medicina Interna', tema:'Reumatología', a:'Monoartritis aguda febril con antecedente de gota. ¿Qué se hace primero?', b:'Artrocentesis. Hay que descartar artritis séptica: la gota no protege de la infección.', mas:'Un Gram negativo NO descarta: sensibilidad ~50%.'},
{id:'T-151', esp:'Medicina Interna', tema:'Reumatología', a:'Lupus activo: ¿qué pasa con el complemento?', b:'BAJA. Se consume al formarse los inmunocomplejos. Y los anti-DNA suben.', mas:'Se usan para vigilar la actividad en el tiempo.'},
{id:'T-152', esp:'Medicina Interna', tema:'Reumatología', a:'Crisis de gota con filtrado glomerular de 30 mL/min. ¿Qué se da?', b:'CORTICOIDE oral. AINE contraindicados, colchicina con ajuste. Nunca iniciar alopurinol en la crisis.', mas:'Los cambios bruscos de uricemia prolongan el ataque.'},
{id:'T-153', esp:'Medicina Interna', tema:'Reumatología', a:'Arteritis de células gigantes con amaurosis. ¿Qué se hace primero?', b:'Pulsos de metilprednisolona 1 g/día × 3 días, ANTES de la biopsia. Objetivo: salvar el otro ojo.', mas:'La biopsia sigue siendo válida días después de empezar.'},
{id:'T-154', esp:'Medicina Interna', tema:'Reumatología', a:'Dolor lumbar inflamatorio: ¿cómo se reconoce?', b:'Mejora con el movimiento, empeora con el reposo, rigidez matutina >30 min, despierta de madrugada.', mas:'El mecánico hace lo contrario.'},
{id:'T-155', esp:'Medicina Interna', tema:'Reumatología', a:'Rótula BAJA frente a rótula ALTA: ¿qué tendón se rompió?', b:'Rótula baja = tendón CUADRICIPITAL (tiraba hacia arriba). Rótula alta = tendón ROTULIANO.', mas:'La rótula se mueve al contrario del tendón roto.'},
{id:'T-156', esp:'Medicina Interna', tema:'Reumatología', a:'Monoartritis nueva en paciente con anti-TNF y corticoides, SIN fiebre', b:'Artritis séptica hasta demostrar lo contrario. Los biológicos borran la fiebre.', mas:'La radiografía es normal los primeros días.'},

/* ===================== PEDIATRÍA ===================== */
{id:'T-170', esp:'Pediatría', tema:'Pediatría general', a:'Planes de hidratación de la OMS: ¿qué define el plan B?', b:'Deshidratación con signos, sin choque. SRO 75 mL/kg en 4 h supervisadas + zinc 10-14 días.', mas:'Beber con avidez ES un signo de deshidratación.'},
{id:'T-171', esp:'Pediatría', tema:'Pediatría general', a:'Bronquiolitis: ¿qué NO funciona?', b:'Ni broncodilatadores, ni corticoides, ni antibióticos, ni radiografía de rutina.', mas:'Solo soporte: hidratación, desobstrucción nasal y oxígeno si hace falta.'},
{id:'T-172', esp:'Pediatría', tema:'Pediatría general', a:'Ictericia en las primeras 24 horas de vida', b:'NUNCA es fisiológica. Buscar hemólisis: incompatibilidad ABO o Rh, G6PD.', mas:'Madre O con hijo A o B es la combinación más frecuente.'},
{id:'T-173', esp:'Pediatría', tema:'Pediatría general', a:'Reanimación neonatal: apnea con FC 80 al minuto. ¿Qué se hace?', b:'Ventilación con presión positiva. En el neonato el problema casi siempre es ventilatorio.', mas:'Compresiones solo si FC <60 tras 30 s de ventilación eficaz.'},
{id:'T-174', esp:'Pediatría', tema:'Pediatría general', a:'Neonato de 25 días con fiebre y BUEN aspecto', b:'Ingreso, estudio completo de sepsis y antibiótico empírico. El aspecto no tiene valor predictivo.', mas:'Hemograma, hemocultivo, orina y punción lumbar.'},
{id:'T-175', esp:'Pediatría', tema:'Pediatría general', a:'Definición de convulsión febril SIMPLE', b:'Generalizada · <15 min · única en 24 h · entre 6 meses y 5 años · exploración normal.', mas:'No requiere punción, ni EEG, ni tratamiento crónico.'},
{id:'T-176', esp:'Pediatría', tema:'Pediatría general', a:'Vómito NO bilioso y proyectil a las 3-6 semanas. ¿Qué alteración analítica?', b:'Estenosis hipertrófica del píloro: alcalosis metabólica hipoclorémica e hipopotasémica.', mas:'Se corrigen líquidos y electrolitos ANTES de operar.'},
{id:'T-177', esp:'Pediatría', tema:'Pediatría general', a:'Vómitos de inicio BRUSCO en lactante que nunca vomitaba', b:'Descartar malrotación con vólvulo: isquemia intestinal en horas.', mas:'El píloro se instaura de forma progresiva, no de golpe.'},
{id:'T-178', esp:'Pediatría', tema:'Pediatría general', a:'Desnutrición aguda grave: ¿cuál es el error que mata?', b:'Realimentar rápido y con muchas calorías: síndrome de realimentación.', mas:'Fase de estabilización con aporte bajo y tomas frecuentes.'},
{id:'T-179', esp:'Pediatría', tema:'Pediatría general', a:'Cardiopatía conotruncal + hipoplasia tímica + hipocalcemia', b:'Deleción 22q11 (DiGeorge). La voz nasal por insuficiencia velofaríngea completa el cuadro.', mas:'Williams se asocia a HIPERcalcemia: es el opuesto.'},
{id:'T-180', esp:'Pediatría', tema:'Pediatría general', a:'Cianosis solo en miembros INFERIORES', b:'Ductus con Eisenmenger: el ductus desemboca después de los troncos supraaórticos.', mas:'El Fallot da cianosis generalizada.'},
{id:'T-181', esp:'Pediatría', tema:'Pediatría general', a:'Hemorragia digestiva baja indolora y abundante en niño pequeño', b:'Divertículo de Meckel. Gammagrafía con pertecnetato Tc-99m.', mas:'El trazador lo capta la mucosa gástrica ectópica.'},
{id:'T-182', esp:'Pediatría', tema:'Pediatría general', a:'Lactancia materna exclusiva: ¿hasta cuándo?', b:'6 meses exclusiva. Después complementaria hasta los 2 años o más.', mas:'No confundir la fase exclusiva con la duración total.'},

/* ===================== GINECOLOGÍA Y OBSTETRICIA ===================== */
{id:'T-200', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Preeclampsia grave: ¿qué fármaco previene la eclampsia?', b:'Sulfato de magnesio. Superior a cualquier otro anticonvulsivo.', mas:'Vigilar reflejos, frecuencia respiratoria y diuresis.'},
{id:'T-201', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Signos de intoxicación por sulfato de magnesio y antídoto', b:'Arreflexia rotuliana (primero) → depresión respiratoria. Antídoto: GLUCONATO DE CALCIO.', mas:'La arreflexia precede a la parada respiratoria.'},
{id:'T-202', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Las cuatro causas de hemorragia posparto, por frecuencia', b:'Tono (atonía, 70-80%) · Trauma · Tejido (restos) · Trombina (coagulopatía).', mas:'Útero blando por encima del ombligo = atonía.'},
{id:'T-203', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Sangrado del 3.er trimestre CON dolor y útero hipertónico', b:'Desprendimiento de placenta. Sin dolor y útero blando: placenta previa.', mas:'En el desprendimiento la sangre visible subestima la real.'},
{id:'T-204', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Sangrado del 3.er trimestre: ¿qué está PROHIBIDO hacer?', b:'El tacto vaginal, hasta localizar la placenta con ecografía.', mas:'Tampoco amniorrexis artificial.'},
{id:'T-205', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Parto pretérmino: ¿qué salva al recién nacido?', b:'Corticoides prenatales entre 24 y 34 semanas. La tocólisis solo gana 48 h para dar tiempo.', mas:'El reposo en cama no previene nada.'},
{id:'T-206', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Profilaxis anti-D: ¿cuándo?', b:'Semana 28 y dentro de las 72 h posparto si el recién nacido es Rh positivo.', mas:'También ante aborto, ectópico, amniocentesis o trauma.'},
{id:'T-207', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Bacteriuria asintomática en el embarazo: ¿se trata?', b:'SÍ, siempre. Es la excepción a la regla general.', mas:'Sin tratar, 20-30% desarrollan pielonefritis.'},
{id:'T-208', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Tamizaje de diabetes gestacional: ¿en qué semanas?', b:'Entre las 24 y 28 semanas.', mas:'Antes solo si hay factores de riesgo, para buscar diabetes previa.'},
{id:'T-209', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Hipertensión detectada ANTES de las 20 semanas', b:'Hipertensión CRÓNICA. Después de las 20: gestacional o preeclampsia.', mas:'Las 20 semanas ordenan toda la clasificación.'},
{id:'T-210', esp:'Ginecología y Obstetricia', tema:'Obstetricia', a:'Ácido fólico: ¿cuándo empezar?', b:'Al menos un mes ANTES de la concepción. El tubo neural cierra en la 4.ª semana.', mas:'Al confirmar el embarazo ya suele ser tarde.'},
{id:'T-211', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Metrorragia posmenopáusica: ¿qué hay que descartar y cómo?', b:'Cáncer de endometrio. Ecografía transvaginal + BIOPSIA ENDOMETRIAL.', mas:'La citología cervical normal no descarta nada: explora el cérvix.'},
{id:'T-212', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Citología con lesión de ALTO grado: ¿siguiente paso?', b:'Colposcopia con biopsia dirigida. La citología criba, la biopsia diagnostica.', mas:'Nunca se trata un cáncer de cérvix con solo una citología.'},
{id:'T-213', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Criterios de Rotterdam para el ovario poliquístico', b:'Dos de tres: oligoovulación · hiperandrogenismo clínico o bioquímico · ovarios poliquísticos en ecografía.', mas:'Y es diagnóstico de EXCLUSIÓN.'},
{id:'T-214', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Migraña CON aura: ¿qué anticoncepción está contraindicada?', b:'Cualquiera con estrógenos: oral, parche o anillo. Categoría 4 de la OMS.', mas:'Cambiar la vía no elimina el riesgo.'},
{id:'T-215', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Aborto de repetición: ¿qué se estudia y qué NO?', b:'Sí: cariotipo de la pareja, cavidad uterina, antifosfolípido y trombofilias, tiroides. NO: reserva folicular.', mas:'La reserva mide fertilidad, no pérdida gestacional.'},
{id:'T-216', esp:'Ginecología y Obstetricia', tema:'Ginecología', a:'Seguimiento tras evacuar una mola', b:'β-hCG semanal hasta 3 negativas consecutivas, luego mensual. Anticoncepción eficaz obligatoria.', mas:'Un embarazo nuevo haría ininterpretable la curva.'},

/* ===================== CIRUGÍA Y EMERGENCIAS ===================== */
{id:'T-230', esp:'Cirugía', tema:'Cirugía general', a:'Fórmula de Parkland y desde cuándo se cuenta el tiempo', b:'4 mL × kg × %SCQ en 24 h; la MITAD en las primeras 8 h, contadas desde la QUEMADURA, no desde el ingreso.', mas:'Se ajusta según diuresis horaria.'},
{id:'T-231', esp:'Cirugía', tema:'Cirugía general', a:'Escarotomía frente a escarectomía', b:'Escarotomía: INCIDE para liberar, es urgente ante compromiso vascular. Escarectomía: EXTIRPA, es diferida.', mas:'La escara circunferencial actúa como torniquete.'},
{id:'T-232', esp:'Cirugía', tema:'Cirugía general', a:'Dolor abdominal desproporcionado con abdomen blando, en paciente con fibrilación auricular', b:'Isquemia mesentérica aguda. Lactato elevado y angiotomografía.', mas:'El intestino sufre antes de que el peritoneo se inflame.'},
{id:'T-233', esp:'Cirugía', tema:'Cirugía general', a:'Apendicitis de 12 días con plastrón y absceso. ¿Se opera ya?', b:'No: antibiótico + drenaje percutáneo, y apendicectomía diferida a las 8-12 semanas.', mas:'Operar sobre el plastrón aumenta mucho la morbilidad.'},
{id:'T-234', esp:'Cirugía', tema:'Cirugía general', a:'Melanoma: ¿desde qué Breslow se hace ganglio centinela?', b:'Desde 0,8 mm. Márgenes: 1 cm para 1-2 mm; 2 cm para >2 mm.', mas:'La linfadenectomía completa ya no es sistemática.'},
{id:'T-235', esp:'Cirugía', tema:'Cirugía general', a:'Necrosis cutánea al iniciar acenocumarol. ¿Qué déficit?', b:'Proteína C. Su vida media corta la hace caer antes que los factores procoagulantes.', mas:'Se previene solapando heparina los primeros días.'},
{id:'T-236', esp:'Emergencias', tema:'Urgencias', a:'Anafilaxia: fármaco, vía y sitio', b:'ADRENALINA intramuscular en la cara anterolateral del muslo. Repetir cada 5-15 min si hace falta.', mas:'Antihistamínico y corticoide no rescatan.'},
{id:'T-237', esp:'Emergencias', tema:'Urgencias', a:'Toxíndrome colinérgico: ¿qué lo distingue de los opioides?', b:'Ambos dan miosis, pero el colinérgico añade secreciones abundantes y FASCICULACIONES.', mas:'Atropina titulada hasta secar las secreciones bronquiales.'},
{id:'T-238', esp:'Emergencias', tema:'Urgencias', a:'Paquete de la primera hora en sepsis', b:'Lactato · hemocultivos ANTES del antibiótico · antibiótico de amplio espectro · cristaloides · vasopresor si no responde.', mas:'Se trata mientras se busca el foco, no al revés.'},
{id:'T-239', esp:'Emergencias', tema:'Urgencias', a:'Shock séptico que no responde a líquidos: ¿noradrenalina o dobutamina?', b:'NORADRENALINA: es un shock distributivo, falta tono vascular. La dobutamina vasodilata y lo empeora.', mas:'Dobutamina solo si hay disfunción miocárdica asociada.'},
{id:'T-240', esp:'Emergencias', tema:'Urgencias', a:'Paro presenciado sin pulso: ¿qué es lo siguiente tras pedir ayuda?', b:'COMPRESIONES torácicas. Y desfibrilar de inmediato si el ritmo es desfibrilable.', mas:'La intubación nunca interrumpe las compresiones.'},
{id:'T-241', esp:'Emergencias', tema:'Urgencias', a:'Escala de Glasgow: ¿qué se confunde siempre?', b:'LOCALIZA el dolor = 5. RETIRA al dolor = 4.', mas:'Se documenta desglosada, no solo el total.'},
{id:'T-242', esp:'Emergencias', tema:'Urgencias', a:'Intoxicación por paracetamol: ¿por qué no se puede esperar?', b:'Es asintomática las primeras 24 h. Nivel a partir de las 4 h y N-acetilcisteína dentro de 8-10 h.', mas:'Esperar la ictericia es esperar al daño hepático.'},
{id:'T-243', esp:'Emergencias', tema:'Urgencias', a:'Golpe de calor: ¿por qué NO usar vasoconstrictores?', b:'Cierran la vía por la que la sangre caliente llega a la piel para disiparse. La hipotensión se trata con volumen.', mas:'El tratamiento es enfriar rápido.'},
{id:'T-244', esp:'Emergencias', tema:'Urgencias', a:'Hipoxemia que NO mejora con oxígeno al 100%', b:'Cortocircuito (shunt): territorio perfundido pero no ventilado. Hay que reexpandir, no subir la FiO₂.', mas:'Si la PaCO₂ está baja, no es hipoventilación.'},

/* ===================== FARMACOLOGÍA ===================== */
{id:'T-260', esp:'Farmacología', tema:'Principios generales', a:'¿Cuántas vidas medias hasta el estado estacionario?', b:'4 a 5. Subir la dosis eleva la meseta pero NO acelera llegar a ella: para eso está la dosis de carga.', mas:'1 vida media = 50%; 2 = 75%; 3 = 87,5%.'},
{id:'T-261', esp:'Farmacología', tema:'Principios generales', a:'Absorción frente a biodisponibilidad', b:'Un fármaco puede absorberse por completo y tener baja biodisponibilidad, por el primer paso hepático.', mas:'Sublingual y rectal baja lo evitan.'},
{id:'T-262', esp:'Farmacología', tema:'Cardiovascular', a:'Tos seca con IECA: ¿mecanismo y solución?', b:'Acumulación de bradicinina. Cambiar a ARA-II (losartán, valsartán), que no la afectan.', mas:'No depende de la dosis y no cede sin retirar el fármaco.'},
{id:'T-263', esp:'Farmacología', tema:'Cardiovascular', a:'Intoxicación digitálica: ¿qué electrolito la potencia?', b:'La HIPOPOTASEMIA. Puede haber toxicidad con digoxinemia normal.', mas:'Halos amarillos, vómitos, confusión y arritmias.'},
{id:'T-264', esp:'Farmacología', tema:'Antimicrobianos', a:'Toxicidad característica de los aminoglucósidos', b:'Nefrotoxicidad (reversible) y ototoxicidad (puede ser permanente).', mas:'Dosis única diaria y vigilar función renal.'},
{id:'T-265', esp:'Farmacología', tema:'Antimicrobianos', a:'Antibióticos contraindicados en el embarazo', b:'Tetraciclinas (dientes y hueso fetal). Seguros: betalactámicos y fosfomicina.', mas:'La seguridad fetal filtra antes que el antibiograma.'},
{id:'T-266', esp:'Farmacología', tema:'Anticoagulación', a:'INR que se dispara al añadir un antibiótico', b:'Interacción por inhibición del CYP2C9 (p. ej. trimetoprim-sulfametoxazol) + menos vitamina K intestinal.', mas:'Cada antibiótico nuevo obliga a controlar el INR.'},
{id:'T-267', esp:'Farmacología', tema:'Analgesia', a:'AINE: un solo mecanismo, dos daños', b:'Inhiben la ciclooxigenasa → menos prostaglandinas → vasoconstricción renal + pérdida de la protección gástrica.', mas:'También antagonizan a IECA y diuréticos: descontrolan la presión.'},
{id:'T-268', esp:'Farmacología', tema:'Analgesia', a:'Dolor neuropático: ¿qué NO funciona y qué sí?', b:'NO: AINE ni paracetamol. SÍ: gabapentinoides, duloxetina, tricíclicos, lidocaína o capsaicina tópicas.', mas:'Lancinante, quemante, en calcetín, con alodinia.'},
{id:'T-269', esp:'Farmacología', tema:'Respiratorio', a:'¿Por qué el propranolol es peligroso en el asma?', b:'Es NO selectivo: bloquea también los beta-2 bronquiales y puede desencadenar broncoespasmo.', mas:'Además reduce la respuesta al salbutamol de rescate.'},
{id:'T-270', esp:'Farmacología', tema:'Cardiovascular', a:'Mialgias con CK >10 veces el límite y orina oscura tras una estatina', b:'Rabdomiólisis: suspender, hidratar y vigilar la función renal.', mas:'El gemfibrozilo asociado multiplica el riesgo.'},
{id:'T-271', esp:'Farmacología', tema:'Psicofármacos', a:'Síndrome serotoninérgico frente a neuroléptico maligno', b:'Serotoninérgico: HORAS, clonus e hiperreflexia, midriasis. Neuroléptico maligno: DÍAS, rigidez en tubo de plomo.', mas:'CK muy alta en el neuroléptico maligno.'},
{id:'T-272', esp:'Farmacología', tema:'Endocrino', a:'Estreñimiento por opioides: ¿desarrolla tolerancia?', b:'NO. Es el único efecto adverso que no cede con el tiempo: laxante profiláctico desde el primer día.', mas:'La somnolencia y las náuseas sí ceden.'},

/* ===================== CIENCIAS BÁSICAS ===================== */
{id:'T-290', esp:'Ciencias Básicas', tema:'Fisiología', a:'Curva de la hemoglobina a la DERECHA: ¿qué la desplaza?', b:'Acidosis, hipercapnia, fiebre y aumento del 2,3-DPG. Menos afinidad, más entrega al tejido.', mas:'Piensa en un músculo en ejercicio: caliente, ácido y con CO₂.'},
{id:'T-291', esp:'Ciencias Básicas', tema:'Fisiología', a:'¿Por qué la hipoxia produce lactato?', b:'Sin oxígeno se para la cadena respiratoria; el piruvato se reduce a lactato para regenerar NAD⁺ y seguir haciendo ATP.', mas:'Por eso el lactato monitoriza la reanimación.'},
{id:'T-292', esp:'Ciencias Básicas', tema:'Fisiología', a:'Cálculo y valor normal de la brecha aniónica', b:'Na − (Cl + HCO₃). Normal 8-12 mEq/L.', mas:'Elevada: cetoacidosis, láctica, uremia, metanol, etilenglicol.'},
{id:'T-293', esp:'Ciencias Básicas', tema:'Genética', a:'Pareja sana con un hijo con enfermedad autosómica recesiva. ¿Riesgo en el siguiente?', b:'25% en CADA embarazo. Haber tenido uno afectado no reduce el riesgo del siguiente.', mas:'50% portador sano, 25% no portador.'},
{id:'T-294', esp:'Ciencias Básicas', tema:'Genética', a:'Madre portadora de enfermedad recesiva ligada al X', b:'50% de los varones afectados y 50% de las hijas portadoras.', mas:'Fallo ovárico precoz en la familia: pista de premutación del X frágil.'},
{id:'T-295', esp:'Ciencias Básicas', tema:'Patología', a:'Célula predominante en la inflamación AGUDA', b:'Neutrófilo, en las primeras 24 h. Después macrófagos.', mas:'Linfocitos y células plasmáticas: inflamación crónica.'},
{id:'T-296', esp:'Ciencias Básicas', tema:'Dermatología', a:'Regla ABCDE del melanoma y error que no se puede cometer', b:'Asimetría, Bordes, Color, Diámetro >6 mm, Evolución. Nunca destruir con crioterapia: biopsia ESCISIONAL.', mas:'El espesor de Breslow define el pronóstico.'},
{id:'T-297', esp:'Ciencias Básicas', tema:'Otorrinolaringología', a:'Dolor al presionar el trago', b:'Otitis externa. En la otitis media el trago no duele.', mas:'Externa maligna en diabético: Pseudomonas y osteomielitis.'},

/* ===================== EPIDEMIOLOGÍA Y SALUD PÚBLICA ===================== */
{id:'T-310', esp:'Epidemiología', tema:'Epidemiología', a:'¿Qué cambia con la prevalencia y qué no?', b:'Sensibilidad y especificidad NO cambian. Los valores predictivos SÍ: si baja la prevalencia, baja el VPP.', mas:'Por eso no se tamiza a poblaciones de bajo riesgo.'},
{id:'T-311', esp:'Epidemiología', tema:'Epidemiología', a:'Cálculo del número necesario a tratar', b:'NNT = 1 / reducción ABSOLUTA del riesgo. Nunca con la relativa.', mas:'12% − 8% = 4% → NNT = 25.'},
{id:'T-312', esp:'Epidemiología', tema:'Epidemiología', a:'Enfermedad rara con latencia de 20 años: ¿qué diseño?', b:'Casos y controles. Medida: razón de momios (odds ratio).', mas:'Una cohorte prospectiva sería inviable en coste y tiempo.'},
{id:'T-313', esp:'Epidemiología', tema:'Epidemiología', a:'Prevalencia = ?', b:'Depende de la INCIDENCIA y de la DURACIÓN. Si el tratamiento alarga la vida sin curar, la prevalencia SUBE.', mas:'Más prevalencia no significa peor salud poblacional.'},
{id:'T-314', esp:'Epidemiología', tema:'Epidemiología', a:'"Los detectados por cribado viven más, pero la mortalidad no cambió"', b:'Sesgo de adelanto diagnóstico. Solo se adelantó el diagnóstico, no se alargó la vida.', mas:'Los programas se evalúan por mortalidad, no por supervivencia.'},
{id:'T-315', esp:'Epidemiología', tema:'Epidemiología', a:'Curva epidémica con pico único y estrecho', b:'Fuente común PUNTUAL. Todos se expusieron a la vez.', mas:'Meseta larga: fuente continua. Ondas sucesivas: persona a persona.'},
{id:'T-316', esp:'Epidemiología', tema:'Epidemiología', a:'Denominador de la razón de mortalidad materna', b:'Por cada 100.000 NACIDOS VIVOS.', mas:'No por mujeres en edad fértil ni por embarazos.'},
{id:'T-317', esp:'Salud Pública', tema:'Salud Pública', a:'Los cuatro niveles de prevención', b:'Primaria: evitar que aparezca. Secundaria: detectar antes de los síntomas. Terciaria: limitar el daño. Cuaternaria: proteger del exceso de medicina.', mas:'La mamografía de cribado es SECUNDARIA.'},
{id:'T-318', esp:'Salud Pública', tema:'Salud Pública', a:'Los cuatro atributos de la atención primaria', b:'Primer contacto accesible · longitudinalidad · integralidad · coordinación.', mas:'Son atributos funcionales, no un escalón de menor calidad.'},
{id:'T-319', esp:'Epidemiología', tema:'Epidemiología', a:'AVAC en el resultado: ¿qué tipo de análisis es?', b:'Coste-UTILIDAD. Si el resultado va en unidades clínicas naturales, es coste-efectividad.', mas:'Coste-beneficio traduce la salud a dinero.'},

/* ===================== BIOÉTICA ===================== */
{id:'T-330', esp:'Bioética', tema:'Bioética', a:'Paciente competente que rechaza una transfusión vital', b:'Se respeta. La beneficencia no autoriza a imponer tratamiento a un adulto competente.', mas:'Discrepar con el médico no es ser incompetente.'},
{id:'T-331', esp:'Bioética', tema:'Bioética', a:'La familia pide que no se le diga el diagnóstico a una paciente competente', b:'Se le pregunta A ELLA cuánta información quiere y a quién informar. El derecho a no saber es suyo, no de la familia.', mas:'La titularidad de la información es del paciente.'},
{id:'T-332', esp:'Bioética', tema:'Bioética', a:'Elementos del consentimiento informado válido', b:'Información comprensible · capacidad · voluntariedad · decisión del propio paciente.', mas:'Es un proceso de comunicación, no una firma.'}

];
